// Generated by CIRCT firtool-1.149.0
module Dcj11PeripheralCore(
  input         clock,
                reset,
                io_peripheralReset,
  input  [21:0] io_busAddress,
                io_busReadAddress,
                io_busWriteAddress,
  input         io_busReadPulse,
                io_busWritePulse,
  input  [15:0] io_busDataIn,
  input  [1:0]  io_busByteEnable,
  output        io_busHit,
  output [15:0] io_busDataOut,
  input  [1:0]  io_interruptAck,
  input  [15:0] io_interruptAckVector,
  input         io_eventAck,
  output [1:0]  io_irq,
  output [15:0] io_irqVector0,
                io_irqVector1,
  output        io_eventN,
                io_rhMemRequestValid,
  input         io_rhMemRequestReady,
  output        io_rhMemRequestWrite,
  output [21:0] io_rhMemRequestAddress,
  output [15:0] io_rhMemRequestData,
  output [1:0]  io_rhMemRequestByteEnable,
  input         io_rhMemResponseValid,
  input  [15:0] io_rhMemResponseData,
  input         io_rhMemResponseError,
                io_uartRx,
  output        io_uartTx,
  input         io_sdMiso,
  output        io_sdSck,
                io_sdMosi,
                io_sdCsN,
                io_sdActive,
  input  [21:0] io_panelAddress,
  input  [15:0] io_panelData,
  output        io_ledI2cSclDriveLow,
                io_ledI2cSdaDriveLow,
                io_ledAddressEnable,
                io_ledDataEnable
);

  wire        _sd_io_block_request_ready;
  wire        _sd_io_block_read_valid;
  wire [7:0]  _sd_io_block_read_bits;
  wire        _sd_io_block_write_ready;
  wire        _sd_io_block_done;
  wire        _sd_io_block_error;
  wire        _sd_io_block_initialized;
  wire        _rh11_io_bus_hit;
  wire [15:0] _rh11_io_bus_dataOut;
  wire        _rh11_io_block_request_valid;
  wire        _rh11_io_block_request_bits_write;
  wire [31:0] _rh11_io_block_request_bits_lba;
  wire        _rh11_io_block_read_ready;
  wire        _rh11_io_block_write_valid;
  wire [7:0]  _rh11_io_block_write_bits;
  wire        _rh11_io_irq;
  wire        _kw11_io_bus_hit;
  wire [15:0] _kw11_io_bus_dataOut;
  wire        _kl11_io_bus_hit;
  wire [15:0] _kl11_io_bus_dataOut;
  wire        _kl11_io_irq;
  wire        deviceReset;
  assign deviceReset = reset | io_peripheralReset;
  Kl11 kl11 (
    .clock                (clock),
    .reset                (deviceReset),
    .io_bus_address       (io_busAddress),
    .io_bus_readAddress   (io_busReadAddress),
    .io_bus_writeAddress  (io_busWriteAddress),
    .io_bus_readPulse     (io_busReadPulse),
    .io_bus_writePulse    (io_busWritePulse),
    .io_bus_dataIn        (io_busDataIn),
    .io_bus_byteEnable    (io_busByteEnable),
    .io_bus_hit           (_kl11_io_bus_hit),
    .io_bus_dataOut       (_kl11_io_bus_dataOut),
    .io_uartRx            (io_uartRx),
    .io_uartTx            (io_uartTx),
    .io_irq               (_kl11_io_irq),
    .io_vector            (io_irqVector0),
    .io_acknowledge       (io_interruptAck[0]),
    .io_acknowledgeVector (io_interruptAckVector)
  );
  Kw11 kw11 (
    .clock               (clock),
    .reset               (deviceReset),
    .io_bus_address      (io_busAddress),
    .io_bus_writeAddress (io_busWriteAddress),
    .io_bus_writePulse   (io_busWritePulse),
    .io_bus_dataIn       (io_busDataIn),
    .io_bus_byteEnable   (io_busByteEnable),
    .io_bus_hit          (_kw11_io_bus_hit),
    .io_bus_dataOut      (_kw11_io_bus_dataOut),
    .io_eventN           (io_eventN),
    .io_acknowledge      (io_eventAck)
  );
  Rh11Rp06 rh11 (
    .clock                          (clock),
    .reset                          (deviceReset),
    .io_bus_address                 (io_busAddress),
    .io_bus_writeAddress            (io_busWriteAddress),
    .io_bus_writePulse              (io_busWritePulse),
    .io_bus_dataIn                  (io_busDataIn),
    .io_bus_byteEnable              (io_busByteEnable),
    .io_bus_hit                     (_rh11_io_bus_hit),
    .io_bus_dataOut                 (_rh11_io_bus_dataOut),
    .io_memory_request_ready        (io_rhMemRequestReady),
    .io_memory_request_valid        (io_rhMemRequestValid),
    .io_memory_request_bits_write   (io_rhMemRequestWrite),
    .io_memory_request_bits_address (io_rhMemRequestAddress),
    .io_memory_request_bits_data    (io_rhMemRequestData),
    .io_memory_responseValid        (io_rhMemResponseValid),
    .io_memory_responseData         (io_rhMemResponseData),
    .io_memory_responseError        (io_rhMemResponseError),
    .io_block_request_ready         (_sd_io_block_request_ready),
    .io_block_request_valid         (_rh11_io_block_request_valid),
    .io_block_request_bits_write    (_rh11_io_block_request_bits_write),
    .io_block_request_bits_lba      (_rh11_io_block_request_bits_lba),
    .io_block_read_ready            (_rh11_io_block_read_ready),
    .io_block_read_valid            (_sd_io_block_read_valid),
    .io_block_read_bits             (_sd_io_block_read_bits),
    .io_block_write_ready           (_sd_io_block_write_ready),
    .io_block_write_valid           (_rh11_io_block_write_valid),
    .io_block_write_bits            (_rh11_io_block_write_bits),
    .io_block_done                  (_sd_io_block_done),
    .io_block_error                 (_sd_io_block_error),
    .io_block_initialized           (_sd_io_block_initialized),
    .io_irq                         (_rh11_io_irq),
    .io_acknowledge                 (io_interruptAck[1])
  );
  SdBlockDevice sd (
    .clock                       (clock),
    .reset                       (reset),
    .io_block_request_ready      (_sd_io_block_request_ready),
    .io_block_request_valid      (_rh11_io_block_request_valid),
    .io_block_request_bits_write (_rh11_io_block_request_bits_write),
    .io_block_request_bits_lba   (_rh11_io_block_request_bits_lba),
    .io_block_read_ready         (_rh11_io_block_read_ready),
    .io_block_read_valid         (_sd_io_block_read_valid),
    .io_block_read_bits          (_sd_io_block_read_bits),
    .io_block_write_ready        (_sd_io_block_write_ready),
    .io_block_write_valid        (_rh11_io_block_write_valid),
    .io_block_write_bits         (_rh11_io_block_write_bits),
    .io_block_done               (_sd_io_block_done),
    .io_block_error              (_sd_io_block_error),
    .io_block_initialized        (_sd_io_block_initialized),
    .io_miso                     (io_sdMiso),
    .io_sck                      (io_sdSck),
    .io_mosi                     (io_sdMosi),
    .io_csN                      (io_sdCsN),
    .io_active                   (io_sdActive)
  );
  Aw21024Panel panel (
    .clock            (clock),
    .reset            (reset),
    .io_addressValue  (io_panelAddress),
    .io_dataValue     (io_panelData),
    .io_sclDriveLow   (io_ledI2cSclDriveLow),
    .io_sdaDriveLow   (io_ledI2cSdaDriveLow),
    .io_addressEnable (io_ledAddressEnable),
    .io_dataEnable    (io_ledDataEnable)
  );
  assign io_busHit = _kl11_io_bus_hit | _kw11_io_bus_hit | _rh11_io_bus_hit;
  assign io_busDataOut =
    _kl11_io_bus_hit
      ? _kl11_io_bus_dataOut
      : _kw11_io_bus_hit
          ? _kw11_io_bus_dataOut
          : _rh11_io_bus_hit ? _rh11_io_bus_dataOut : 16'h0;
  assign io_irq = {_rh11_io_irq, _kl11_io_irq};
  assign io_irqVector1 = 16'hAC;
  assign io_rhMemRequestByteEnable = 2'h3;
endmodule

