// Generated by CIRCT firtool-1.149.0
module Rh11Rp06(
  input         clock,
                reset,
  input  [21:0] io_bus_address,
                io_bus_writeAddress,
  input         io_bus_writePulse,
  input  [15:0] io_bus_dataIn,
  input  [1:0]  io_bus_byteEnable,
  output        io_bus_hit,
  output [15:0] io_bus_dataOut,
  input         io_memory_request_ready,
  output        io_memory_request_valid,
                io_memory_request_bits_write,
  output [21:0] io_memory_request_bits_address,
  output [15:0] io_memory_request_bits_data,
  input         io_memory_responseValid,
  input  [15:0] io_memory_responseData,
  input         io_memory_responseError,
                io_block_request_ready,
  output        io_block_request_valid,
                io_block_request_bits_write,
  output [31:0] io_block_request_bits_lba,
  output        io_block_read_ready,
  input         io_block_read_valid,
  input  [7:0]  io_block_read_bits,
  input         io_block_write_ready,
  output        io_block_write_valid,
  output [7:0]  io_block_write_bits,
  input         io_block_done,
                io_block_error,
                io_block_initialized,
  output        io_irq,
  input         io_acknowledge
);

  wire [7:0]  _partialSector_ext_R0_data;
  reg  [15:0] wc;
  reg  [15:0] ba;
  reg  [15:0] da;
  reg  [15:0] cs2;
  reg  [15:0] er1;
  reg  [15:0] of;
  reg  [15:0] dc;
  reg  [5:0]  bae;
  reg  [4:0]  function_0;
  reg         ie;
  reg         ready;
  reg         volumeValid;
  reg         pending;
  reg         attention;
  reg  [31:0] lba;
  reg  [4:0]  state;
  reg  [7:0]  lowByte;
  reg  [15:0] wordData;
  reg  [9:0]  sectorByte;
  reg         commandWrite;
  wire        _partialSectorRead_T_1;
  wire        _GEN;
  wire        _GEN_0;
  wire        _GEN_1;
  wire [23:0] _GEN_2;
  wire        specialCondition;
  wire        busy_layerCapture;
  wire [21:0] wordAddress;
  wire [21:0] _offset_T;
  wire        _io_block_request_bits_write_T;
  wire        _GEN_3;
  wire        _GEN_4;
  wire        _GEN_5;
  wire        _GEN_6;
  wire        _GEN_7;
  wire        _GEN_8;
  wire        _GEN_9;
  wire        _GEN_10;
  wire        _GEN_11;
  wire        _GEN_12;
  wire        _GEN_13;
  wire        _GEN_14;
  wire        io_block_read_ready_0;
  wire        _GEN_15;
  wire        _GEN_16;
  wire        io_memory_request_valid_0;
  wire        _GEN_17;
  wire        io_block_request_valid_0;
  wire        _GEN_18;
  wire        io_block_write_valid_0;
  wire        _GEN_19;
  wire        _GEN_20;
  wire        _GEN_21;
  wire [21:0] _GEN_22;
  wire [21:0] _nextAddress_T;
  wire [21:0] _nextAddress_T_1;
  wire        _GEN_23;
  wire        _GEN_24;
  wire        _GEN_25;
  wire        _GEN_26;
  wire [13:0] _GEN_27;
  wire [11:0] _GEN_28;
  wire        _GEN_29;
  wire        _GEN_30;
  wire        _GEN_31;
  wire        _GEN_32;
  wire        _GEN_33;
  wire        _GEN_34;
  wire        _GEN_35;
  wire        _GEN_36;
  wire        _GEN_37;
  wire        addressValid;
  wire [25:0] _computedLba_T_4;
  wire [21:0] writeWordAddress;
  wire [21:0] _writeOffset_T;
  wire        _GEN_38;
  wire        _GEN_39;
  wire        _GEN_40;
  wire        _GEN_41;
  wire [6:0]  _merged_T_7;
  wire [5:0]  _bae_T_2;
  wire        _GEN_42;
  wire        _GEN_43;
  wire [12:0] _GEN_44;
  wire [15:0] _cs2_T;
  wire        _GEN_45;
  wire        _GEN_46;
  wire        _GEN_47;
  wire [10:0] _GEN_48;
  wire [15:0] _er1_T_1;
  wire        _GEN_49;
  wire        _GEN_50;
  wire        _GEN_51;
  wire [15:0] _da_T;
  wire        _GEN_52;
  wire [15:0] _GEN_53;
  wire        _GEN_54;
  wire        _GEN_55;
  wire        _GEN_56;
  wire        _GEN_57;
  wire        _GEN_58;
  wire        _GEN_59;
  wire        _GEN_60;
  wire        _GEN_61;
  wire [15:0] _er1_T_2;
  wire        _GEN_62;
  wire [15:0] _er1_T_3;
  wire        _GEN_63;
  wire [14:0] _GEN_64;
  wire [15:0] _er1_T_4;
  wire [15:0] _cs2_T_6;
  wire [15:0] _er1_T_6;
  wire [15:0] _er1_T_7;
  wire        _GEN_65;
  wire [9:0]  _GEN_66;
  wire [15:0] _er1_T_8;
  wire        _GEN_67;
  wire        _GEN_68;
  wire        _GEN_69;
  wire [31:0] _GEN_70;
  wire [4:0]  _GEN_71;
  wire        _GEN_72;
  wire [15:0] _er1_T_9;
  wire [15:0] _cs2_T_11;
  wire [15:0] _er1_T_11;
  wire [15:0] _er1_T_12;
  wire        _GEN_73;
  wire        _GEN_74;
  wire        _GEN_75;
  wire        _GEN_76;
  wire        _GEN_77;
  wire        _GEN_78;
  wire        _GEN_79;
  wire        _GEN_80;
  wire        _GEN_81;
  wire        _GEN_82;
  wire        _GEN_83;
  wire        _GEN_84;
  wire [4:0]  _GEN_85;
  wire        _GEN_86;
  wire [15:0] _wc_T_8;
  wire        _GEN_87;
  wire        _GEN_88;
  wire [15:0] _ba_T_9;
  wire        _GEN_89;
  wire        _GEN_90;
  wire [15:0] _da_T_9;
  wire        _GEN_91;
  wire        _GEN_92;
  wire [5:0]  _merged_T_15;
  wire        _GEN_93;
  wire        _GEN_94;
  wire        _GEN_95;
  wire        _GEN_96;
  wire        _GEN_97;
  wire        _GEN_98;
  wire [15:0] _GEN_99;
  wire        _GEN_100;
  wire [15:0] _GEN_101;
  wire        _GEN_102;
  wire        _GEN_103;
  wire        _GEN_104;
  wire        _GEN_105;
  wire [15:0] _dc_T_8;
  wire        _GEN_106;
  wire        _GEN_107;
  wire        _GEN_108;
  wire        _GEN_109;
  wire        _GEN_110;
  wire        _GEN_111;
  wire        _GEN_112;
  wire        _GEN_113;
  wire        _GEN_114;
  wire        _GEN_115;
  wire        _GEN_116;
  wire        _GEN_117;
  wire        _GEN_118;
  wire        _GEN_119;
  wire        _GEN_120;
  wire        _GEN_121;
  wire        _GEN_122;
  wire        _GEN_123;
  wire        _GEN_124;
  wire        _GEN_125;
  assign _partialSectorRead_T_1 = state == 5'hC;
  assign _GEN = state == 5'hD;
  assign _GEN_0 = state == 5'hE;
  assign _GEN_1 = state == 5'hF;
  assign _GEN_2 = {er1, cs2[15:8]};
  assign specialCondition = (|_GEN_2) | attention;
  assign busy_layerCapture = |state;
  assign wordAddress = {io_bus_address[21:1], 1'h0};
  assign _offset_T = {io_bus_address[21:1], 1'h0} + 22'h240;
  assign _io_block_request_bits_write_T = state == 5'h10;
  assign _GEN_3 = state == 5'h0;
  assign _GEN_4 = state == 5'h1;
  assign _GEN_5 = lba > 32'h530B9;
  assign _GEN_6 = state == 5'h2;
  assign _GEN_7 = state == 5'h3;
  assign _GEN_8 = state == 5'h4;
  assign _GEN_9 = state == 5'h5;
  assign _GEN_10 = state == 5'h11;
  assign _GEN_11 = state == 5'h12;
  assign _GEN_12 = state == 5'h6;
  assign _GEN_13 = _GEN_6 | _GEN_7;
  assign _GEN_14 = _GEN_3 | _GEN_4;
  assign io_block_read_ready_0 =
    ~_GEN_14 & (_GEN_13 | ~(_GEN_8 | _GEN_9) & (_GEN_10 | ~_GEN_11 & _GEN_12));
  assign _GEN_15 = state == 5'h7;
  assign _GEN_16 = _GEN_14 | _GEN_6 | _GEN_7;
  assign io_memory_request_valid_0 =
    ~_GEN_16 & (_GEN_8 | ~(_GEN_9 | _GEN_10 | _GEN_11 | _GEN_12) & _GEN_15);
  assign _GEN_17 = state == 5'h8;
  assign io_block_request_valid_0 =
    ~_GEN_3
    & (_GEN_4
         ? ~(_GEN_5 | commandWrite)
         : ~(_GEN_13 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_15 | _GEN_17
             | _GEN | _GEN_0 | _GEN_1) & _io_block_request_bits_write_T);
  assign _GEN_18 = state == 5'hB;
  assign io_block_write_valid_0 =
    ~(_GEN_16 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | _GEN_15 | _GEN_17 | _GEN
      | _GEN_0 | _GEN_1 | _io_block_request_bits_write_T) & _GEN_18;
  assign _GEN_19 = ~io_memory_responseValid | io_memory_responseError;
  assign _GEN_20 = ~io_memory_responseValid | io_memory_responseError | ~_GEN_5;
  assign _GEN_21 = _GEN_10 | _GEN_11 | _GEN_12 | _GEN_15 | _GEN_17 | _GEN | ~_GEN_0;
  assign _GEN_22 = {bae, ba};
  assign _nextAddress_T = _GEN_22 + 22'h2;
  assign _nextAddress_T_1 = _GEN_22 + 22'h2;
  assign _GEN_23 = _GEN_5 & commandWrite;
  assign _GEN_24 = _GEN_5 & (&wc);
  assign _GEN_25 = io_memory_responseValid & io_memory_responseError & _GEN_5;
  assign _GEN_26 = io_memory_responseValid & io_memory_responseError;
  assign _GEN_27 = er1[13:0] | 14'h2000;
  assign _GEN_28 = cs2[11:0] | 12'h800;
  assign _GEN_29 = (&wc) & sectorByte != 10'h1FF;
  assign _GEN_30 = sectorByte == 10'h1FF;
  assign _GEN_31 = (&wc) | _GEN_30;
  assign _GEN_32 = io_block_write_ready & io_block_write_valid_0;
  assign _GEN_33 = sectorByte == 10'h200;
  assign _GEN_34 = io_memory_request_ready & io_memory_request_valid_0;
  assign _GEN_35 = io_block_read_ready_0 & io_block_read_valid;
  assign _GEN_36 = _GEN_33 | ~_GEN_35;
  assign _GEN_37 = io_block_request_ready & io_block_request_valid_0;
  assign addressValid = dc < 16'h32F & da[12:8] < 5'h13 & da[4:0] < 5'h16;
  assign _computedLba_T_4 =
    {5'h0, {5'h0, dc} * 21'h13 + {16'h0, da[12:8]}} * 26'h16 + {21'h0, da[4:0]};
  assign writeWordAddress = {io_bus_writeAddress[21:1], 1'h0};
  assign _writeOffset_T = {io_bus_writeAddress[21:1], 1'h0} + 22'h240;
  assign _GEN_38 = ~io_acknowledge & pending;
  assign _GEN_39 = ~io_acknowledge & ie;
  assign _GEN_40 =
    io_bus_writePulse & writeWordAddress > 22'h3FFDBF & writeWordAddress < 22'h3FFDEB
    & _GEN_3;
  assign _GEN_41 = _writeOffset_T == 22'h0;
  assign _merged_T_7 =
    io_bus_byteEnable[0] ? io_bus_dataIn[6:0] : {ie, function_0, busy_layerCapture};
  assign _bae_T_2 = {bae[5:2], io_bus_byteEnable[1] ? io_bus_dataIn[9:8] : bae[1:0]};
  assign _GEN_42 = io_bus_byteEnable[0] & io_bus_dataIn[7] & io_bus_dataIn[6];
  assign _GEN_43 = _GEN_42 | _GEN_38;
  assign _GEN_44 = cs2[12:0] | 13'h1000;
  assign _cs2_T = {cs2[15:13], _GEN_44};
  assign _GEN_45 = ~ready & ie;
  assign _GEN_46 = _GEN_45 | _GEN_42 | _GEN_38;
  assign _GEN_47 = _merged_T_7[5:1] == 5'h2;
  assign _GEN_48 = er1[10:0] | 11'h400;
  assign _er1_T_1 = {er1[15:11], _GEN_48};
  assign _GEN_49 = ~addressValid | ready;
  assign _GEN_50 = addressValid ? _GEN_43 : _GEN_46;
  assign _GEN_51 = _merged_T_7[5:1] == 5'h3;
  assign _da_T = {da[15:8], 8'h0};
  assign _GEN_52 = _merged_T_7[5:1] == 5'h4;
  assign _GEN_53 = {8'h0, cs2[7:0]};
  assign _GEN_54 = _merged_T_7[5:1] == 5'h8;
  assign _GEN_55 = _GEN_52 | ~_GEN_54;
  assign _GEN_56 = (|(cs2[2:0])) | _GEN_47;
  assign _GEN_57 = ~(_merged_T_7[0]) | _GEN_56 | ~(_GEN_51 | ~_GEN_55);
  assign _GEN_58 = ~(_merged_T_7[0]) | _GEN_56;
  assign _GEN_59 = _merged_T_7[5:1] == 5'h9;
  assign _GEN_60 = _GEN_54 | _GEN_59;
  assign _GEN_61 = _merged_T_7[5:1] == 5'hC;
  assign _er1_T_2 = {er1[15:11], _GEN_48};
  assign _GEN_62 = _merged_T_7[5:1] == 5'h14;
  assign _er1_T_3 = {er1[15:1], 1'h1};
  assign _GEN_63 = _merged_T_7[5:1] == 5'h18;
  assign _GEN_64 = er1[14:0] | 15'h4000;
  assign _er1_T_4 = {er1[15], _GEN_64};
  assign _cs2_T_6 = {cs2[15:13], _GEN_44};
  assign _er1_T_6 = {er1[15], _GEN_64};
  assign _er1_T_7 = {er1[15:11], _GEN_48};
  assign _GEN_65 = _computedLba_T_4 > 26'h530B9;
  assign _GEN_66 = er1[9:0] | 10'h200;
  assign _er1_T_8 = {er1[15:10], _GEN_66};
  assign _GEN_67 = io_block_initialized & (|(cs2[2:0]));
  assign _GEN_68 = (|{~io_block_initialized, cs2[2:0]}) | ~volumeValid | ~addressValid;
  assign _GEN_69 =
    ~io_block_initialized | (|(cs2[2:0])) | ~volumeValid | ~addressValid | _GEN_65;
  assign _GEN_70 = {6'h0, _computedLba_T_4};
  assign _GEN_71 = _GEN_69 ? 5'hA : 5'h1;
  assign _GEN_72 = _merged_T_7[5:1] == 5'h1C;
  assign _er1_T_9 = {er1[15], _GEN_64};
  assign _cs2_T_11 = {cs2[15:13], _GEN_44};
  assign _er1_T_11 = {er1[15], _GEN_64};
  assign _er1_T_12 = {er1[15:11], _GEN_48};
  assign _GEN_73 = ~(_merged_T_7[0]) | (|(cs2[2:0]));
  assign _GEN_74 = _GEN_72 & io_block_initialized & (|(cs2[2:0]));
  assign _GEN_75 = _GEN_54 | _GEN_59 | _GEN_61 | _GEN_62;
  assign _GEN_76 = _GEN_47 | _GEN_51;
  assign _GEN_77 =
    _GEN_56 | _GEN_51 | ~_GEN_52
    & (_GEN_60 | _GEN_61 | _GEN_62
       | (_GEN_63 ? _GEN_68 | _GEN_65 | attention : _GEN_72 & _GEN_68 | attention));
  assign _GEN_78 = ~io_block_initialized | (|(cs2[2:0])) | ~volumeValid | ~addressValid;
  assign _GEN_79 = ~_GEN_72 | _GEN_78;
  assign _GEN_80 = (|(cs2[2:0])) | _GEN_47 | _GEN_51 | _GEN_52 | _GEN_75;
  assign _GEN_81 = _GEN_40 & _GEN_41 & _merged_T_7[0];
  assign _GEN_82 = ~_GEN_81 | _GEN_80 | (_GEN_63 ? _GEN_69 : _GEN_79);
  assign _GEN_83 = _GEN_51 | _GEN_52 | _GEN_60;
  assign _GEN_84 =
    (|(cs2[2:0]))
    | (_GEN_47
         ? _GEN_49
         : _GEN_83
             ? ready
             : _GEN_61
                 ? _GEN_49
                 : _GEN_62 | (_GEN_63 ? _GEN_68 | _GEN_65 : _GEN_72 ? _GEN_68 : ready));
  assign _GEN_85 = _GEN_78 ? 5'hA : 5'h1;
  assign _GEN_86 = _writeOffset_T == 22'h2;
  assign _wc_T_8 =
    {io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : wc[15:8],
     io_bus_byteEnable[0] ? io_bus_dataIn[7:0] : wc[7:0]};
  assign _GEN_87 = ~_GEN_40 | _GEN_41 | ~_GEN_86;
  assign _GEN_88 = _writeOffset_T == 22'h4;
  assign _ba_T_9 =
    {io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : ba[15:8],
     io_bus_byteEnable[0] ? io_bus_dataIn[7:1] : ba[7:1],
     1'h0};
  assign _GEN_89 = ~_GEN_40 | _GEN_41 | _GEN_86 | ~_GEN_88;
  assign _GEN_90 = _writeOffset_T == 22'h6;
  assign _da_T_9 =
    {io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : da[15:8],
     io_bus_byteEnable[0] ? io_bus_dataIn[7:0] : da[7:0]};
  assign _GEN_91 = _GEN_86 | _GEN_88 | ~_GEN_90;
  assign _GEN_92 = _writeOffset_T == 22'h8;
  assign _merged_T_15 = io_bus_byteEnable[0] ? io_bus_dataIn[5:0] : cs2[5:0];
  assign _GEN_93 = _merged_T_15[5] | io_acknowledge;
  assign _GEN_94 = _GEN_86 | _GEN_88 | _GEN_90;
  assign _GEN_95 = _GEN_94 | ~_GEN_92;
  assign _GEN_96 =
    _GEN_40
      ? (_GEN_41
           ? (_merged_T_7[0]
                ? ((|(cs2[2:0]))
                     ? _GEN_46
                     : _GEN_47
                         ? _GEN_50
                         : _GEN_83
                             ? _GEN_43
                             : _GEN_61
                                 ? _GEN_50
                                 : _GEN_62
                                     ? _GEN_46
                                     : _GEN_63
                                         ? (~io_block_initialized | (|(cs2[2:0]))
                                            | ~volumeValid | ~addressValid | _GEN_65)
                                           & _GEN_46
                                         : _GEN_72
                                             ? (~io_block_initialized | (|(cs2[2:0]))
                                                | ~volumeValid | ~addressValid) & _GEN_46
                                             : _GEN_43)
                : _GEN_43)
           : _GEN_95 ? _GEN_38 : ~_GEN_93 & pending)
      : _GEN_38;
  assign _GEN_97 = _GEN_92 & _merged_T_15[5];
  assign _GEN_98 = ~_GEN_94 & _GEN_97 | ready;
  assign _GEN_99 = _merged_T_15[5] ? 16'h0 : {cs2[15:3], _merged_T_15[2:0]};
  assign _GEN_100 = _writeOffset_T == 22'hC;
  assign _GEN_101 =
    ({16{~_GEN_100}}
     | ~{io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : 8'h0,
         io_bus_byteEnable[0] ? io_bus_dataIn[7:0] : 8'h0}) & er1;
  assign _GEN_102 = _writeOffset_T == 22'hE;
  assign _GEN_103 =
    _GEN_92 ? ~(_merged_T_15[5]) & attention : (_GEN_100 | ~_GEN_102) & attention;
  assign _GEN_104 = _writeOffset_T == 22'h1A;
  assign _GEN_105 = _writeOffset_T == 22'h1C;
  assign _dc_T_8 =
    {io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : dc[15:8],
     io_bus_byteEnable[0] ? io_bus_dataIn[7:0] : dc[7:0]};
  assign _GEN_106 =
    _GEN_86 | _GEN_88 | _GEN_90 | _GEN_92 | _GEN_100 | _GEN_102 | _GEN_104 | ~_GEN_105;
  assign _GEN_107 =
    _GEN_86 | _GEN_88 | _GEN_90 | _GEN_92 | _GEN_100 | _GEN_102 | _GEN_104 | _GEN_105
    | ~(_writeOffset_T == 22'h28 & io_bus_byteEnable[0]);
  assign _GEN_108 = sectorByte == 10'h1FE;
  assign _GEN_109 = _GEN_12 | _GEN_15;
  assign _GEN_110 = _GEN_6 | _GEN_7 | _GEN_8;
  assign _GEN_111 = state == 5'h9;
  assign _GEN_112 =
    _GEN | _GEN_0 | _GEN_1 | _io_block_request_bits_write_T | _GEN_18
    | _partialSectorRead_T_1;
  assign _GEN_113 = wc == 16'h0;
  assign _GEN_114 = _GEN_112 | ~_GEN_111;
  assign _GEN_115 = da[4:0] == 5'h15;
  assign _GEN_116 = da[12:8] == 5'h12;
  assign _GEN_117 = _GEN_115 & _GEN_116;
  assign _GEN_118 = _GEN_10 | _GEN_11 | _GEN_12 | _GEN_15 | _GEN_17 | _GEN_112;
  assign _GEN_119 = _GEN_118 | ~_GEN_111 | io_block_error | ~io_block_done;
  assign _GEN_120 =
    _GEN_40 ? (_GEN_41 ? (_merged_T_7[0] ? _GEN_84 : ready) : _GEN_98) : ready;
  assign _GEN_121 =
    _GEN_40
      ? (_GEN_41
           ? (_merged_T_7[0] ? _GEN_77 : attention)
           : _GEN_94 ? attention : _GEN_103)
      : attention;
  assign _GEN_122 = io_block_done & _GEN_113;
  assign _GEN_123 = _GEN_111 & io_block_error;
  assign _GEN_124 = (|(cs2[2:0])) | _GEN_47 | _GEN_51 | _GEN_52;
  assign _GEN_125 = _GEN_94 | ~_GEN_97;
  always @(posedge clock) begin
    if (reset) begin
      wc <= 16'h0;
      ba <= 16'h0;
      da <= 16'h0;
      cs2 <= 16'h0;
      er1 <= 16'h0;
      of <= 16'h0;
      dc <= 16'h0;
      bae <= 6'h0;
      function_0 <= 5'h0;
      ie <= 1'h0;
      ready <= 1'h1;
      volumeValid <= 1'h0;
      pending <= 1'h0;
      attention <= 1'h0;
      lba <= 32'h0;
      state <= 5'h0;
      lowByte <= 8'h0;
      wordData <= 16'h0;
      sectorByte <= 10'h0;
      commandWrite <= 1'h0;
    end
    else begin
      if (_GEN_3 | _GEN_4 | _GEN_110) begin
        if (_GEN_87) begin
        end
        else
          wc <= _wc_T_8;
        if (_GEN_89) begin
        end
        else
          ba <= _ba_T_9;
        if (_GEN_40) begin
          if (_GEN_41) begin
            if (_GEN_58) begin
            end
            else if (_GEN_51)
              da <= _da_T;
            else if (_GEN_55) begin
            end
            else
              da <= 16'h0;
            if (_GEN_57) begin
            end
            else
              dc <= 16'h0;
            bae <= _bae_T_2;
          end
          else begin
            if (_GEN_91) begin
            end
            else
              da <= _da_T_9;
            if (_GEN_106) begin
            end
            else
              dc <= _dc_T_8;
            if (_GEN_107) begin
            end
            else
              bae <= io_bus_dataIn[5:0];
          end
        end
        if (_GEN_82) begin
        end
        else
          lba <= _GEN_70;
      end
      else if (_GEN_9) begin
        if (_GEN_19) begin
          if (_GEN_87) begin
          end
          else
            wc <= _wc_T_8;
          if (_GEN_89) begin
          end
          else
            ba <= _ba_T_9;
        end
        else begin
          wc <= wc + 16'h1;
          ba <= _nextAddress_T[15:0];
        end
        if (_GEN_20) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_58) begin
              end
              else if (_GEN_51)
                da <= _da_T;
              else if (_GEN_55) begin
              end
              else
                da <= 16'h0;
              if (_GEN_57) begin
              end
              else
                dc <= 16'h0;
            end
            else begin
              if (_GEN_91) begin
              end
              else
                da <= _da_T_9;
              if (_GEN_106) begin
              end
              else
                dc <= _dc_T_8;
            end
          end
        end
        else if (&wc) begin
          da <=
            _GEN_115 ? (_GEN_116 ? 16'h0 : {3'h0, da[12:8] + 5'h1, 8'h0}) : da + 16'h1;
          if (_GEN_117)
            dc <= dc + 16'h1;
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_57) begin
              end
              else
                dc <= 16'h0;
            end
            else if (_GEN_106) begin
            end
            else
              dc <= _dc_T_8;
          end
        end
        else begin
          if (_GEN_108)
            da <=
              _GEN_115 ? (_GEN_116 ? 16'h0 : {3'h0, da[12:8] + 5'h1, 8'h0}) : da + 16'h1;
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_58) begin
              end
              else if (_GEN_51)
                da <= _da_T;
              else if (_GEN_55) begin
              end
              else
                da <= 16'h0;
            end
            else if (_GEN_91) begin
            end
            else
              da <= _da_T_9;
          end
          if (_GEN_108 & _GEN_117)
            dc <= dc + 16'h1;
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_57) begin
              end
              else
                dc <= 16'h0;
            end
            else if (_GEN_106) begin
            end
            else
              dc <= _dc_T_8;
          end
        end
        if (_GEN_19) begin
          if (_GEN_40) begin
            if (_GEN_41)
              bae <= _bae_T_2;
            else if (_GEN_107) begin
            end
            else
              bae <= io_bus_dataIn[5:0];
          end
        end
        else
          bae <= _nextAddress_T[21:16];
        if (_GEN_20) begin
          if (_GEN_82) begin
          end
          else
            lba <= _GEN_70;
        end
        else if (&wc)
          lba <= lba + 32'h1;
        else if (_GEN_108)
          lba <= lba + 32'h1;
        else if (_GEN_82) begin
        end
        else
          lba <= _GEN_70;
      end
      else begin
        if (_GEN_21) begin
          if (_GEN_87) begin
          end
          else
            wc <= _wc_T_8;
          if (_GEN_89) begin
          end
          else
            ba <= _ba_T_9;
        end
        else begin
          wc <= wc + 16'h1;
          ba <= _nextAddress_T_1[15:0];
        end
        if (_GEN_119) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_58) begin
              end
              else if (_GEN_51)
                da <= _da_T;
              else if (_GEN_55) begin
              end
              else
                da <= 16'h0;
            end
            else if (_GEN_91) begin
            end
            else
              da <= _da_T_9;
          end
        end
        else
          da <=
            _GEN_113
              ? (_GEN_115
                   ? (_GEN_116 ? 16'h0 : {3'h0, da[12:8] + 5'h1, 8'h0})
                   : da + 16'h1)
              : _GEN_115
                  ? (_GEN_116 ? 16'h0 : {3'h0, da[12:8] + 5'h1, 8'h0})
                  : da + 16'h1;
        if (_GEN_118 | ~_GEN_111 | io_block_error | ~(io_block_done & _GEN_117)) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_GEN_57) begin
              end
              else
                dc <= 16'h0;
            end
            else if (_GEN_106) begin
            end
            else
              dc <= _dc_T_8;
          end
        end
        else
          dc <= _GEN_113 ? dc + 16'h1 : dc + 16'h1;
        if (_GEN_21) begin
          if (_GEN_40) begin
            if (_GEN_41)
              bae <= _bae_T_2;
            else if (_GEN_107) begin
            end
            else
              bae <= io_bus_dataIn[5:0];
          end
        end
        else
          bae <= _nextAddress_T_1[21:16];
        if (_GEN_119) begin
          if (_GEN_82) begin
          end
          else
            lba <= _GEN_70;
        end
        else
          lba <= _GEN_113 ? lba + 32'h1 : lba + 32'h1;
      end
      if (_GEN_3) begin
        if (_GEN_40) begin
          if (_GEN_41) begin
            if (_merged_T_7[0]) begin
              if (|(cs2[2:0]))
                cs2 <= _cs2_T;
              else if (~_GEN_76) begin
                if (_GEN_52)
                  cs2 <= _GEN_53;
                else if (~_GEN_75) begin
                  if (_GEN_63) begin
                    if (_GEN_67)
                      cs2 <= _cs2_T_6;
                  end
                  else if (_GEN_74)
                    cs2 <= _cs2_T_11;
                end
              end
              ready <= _GEN_84;
              attention <= _GEN_77;
            end
            if (_GEN_73) begin
            end
            else if (_GEN_47) begin
              if (~addressValid)
                er1 <= _er1_T_1;
            end
            else if (~_GEN_51) begin
              if (_GEN_52)
                er1 <= 16'h0;
              else if (~_GEN_60) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    er1 <= _er1_T_2;
                end
                else if (_GEN_62)
                  er1 <= _er1_T_3;
                else if (_GEN_63) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (addressValid) begin
                          if (_GEN_65)
                            er1 <= _er1_T_8;
                        end
                        else
                          er1 <= _er1_T_7;
                      end
                      else
                        er1 <= _er1_T_6;
                    end
                  end
                  else
                    er1 <= _er1_T_4;
                end
                else if (_GEN_72) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (~addressValid)
                          er1 <= _er1_T_12;
                      end
                      else
                        er1 <= _er1_T_11;
                    end
                  end
                  else
                    er1 <= _er1_T_9;
                end
              end
            end
          end
          else begin
            if (_GEN_95) begin
            end
            else
              cs2 <= _GEN_99;
            if (~_GEN_94) begin
              if (_GEN_92) begin
                if (_merged_T_15[5])
                  er1 <= 16'h0;
              end
              else
                er1 <= _GEN_101;
              attention <= _GEN_103;
            end
            ready <= _GEN_98;
          end
        end
        if (_GEN_81) begin
          if (|(cs2[2:0]))
            state <= 5'hA;
          else if (_GEN_47) begin
            if (~addressValid)
              state <= 5'hA;
          end
          else if (~_GEN_83) begin
            if (_GEN_61) begin
              if (~addressValid)
                state <= 5'hA;
            end
            else if (_GEN_62)
              state <= 5'hA;
            else if (_GEN_63)
              state <= _GEN_71;
            else if (_GEN_72)
              state <= _GEN_85;
          end
        end
        if (_GEN_82) begin
        end
        else
          sectorByte <= 10'h0;
      end
      else if (_GEN_4) begin
        if (_GEN_23 | ~_GEN_40) begin
        end
        else if (_GEN_41) begin
          if (_merged_T_7[0]) begin
            if (|(cs2[2:0]))
              cs2 <= _cs2_T;
            else if (~_GEN_76) begin
              if (_GEN_52)
                cs2 <= _GEN_53;
              else if (~_GEN_75) begin
                if (_GEN_63) begin
                  if (_GEN_67)
                    cs2 <= _cs2_T_6;
                end
                else if (_GEN_74)
                  cs2 <= _cs2_T_11;
              end
            end
          end
        end
        else if (_GEN_95) begin
        end
        else
          cs2 <= _GEN_99;
        if (_GEN_23)
          er1 <= {er1[15:10], _GEN_66};
        else if (_GEN_40) begin
          if (_GEN_41) begin
            if (_GEN_73) begin
            end
            else if (_GEN_47) begin
              if (~addressValid)
                er1 <= _er1_T_1;
            end
            else if (~_GEN_51) begin
              if (_GEN_52)
                er1 <= 16'h0;
              else if (~_GEN_60) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    er1 <= _er1_T_2;
                end
                else if (_GEN_62)
                  er1 <= _er1_T_3;
                else if (_GEN_63) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (addressValid) begin
                          if (_GEN_65)
                            er1 <= _er1_T_8;
                        end
                        else
                          er1 <= _er1_T_7;
                      end
                      else
                        er1 <= _er1_T_6;
                    end
                  end
                  else
                    er1 <= _er1_T_4;
                end
                else if (_GEN_72) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (~addressValid)
                          er1 <= _er1_T_12;
                      end
                      else
                        er1 <= _er1_T_11;
                    end
                  end
                  else
                    er1 <= _er1_T_9;
                end
              end
            end
          end
          else if (~_GEN_94) begin
            if (_GEN_92) begin
              if (_merged_T_15[5])
                er1 <= 16'h0;
            end
            else
              er1 <= _GEN_101;
          end
        end
        ready <= _GEN_23 | _GEN_120;
        attention <= _GEN_23 | _GEN_121;
        if (_GEN_5) begin
          state <= commandWrite ? 5'hA : 5'h4;
          if (_GEN_82) begin
          end
          else
            sectorByte <= 10'h0;
        end
        else begin
          if (commandWrite)
            state <= 5'h7;
          else if (_GEN_37)
            state <= 5'h2;
          else if (_GEN_81) begin
            if (|(cs2[2:0]))
              state <= 5'hA;
            else if (_GEN_47) begin
              if (~addressValid)
                state <= 5'hA;
            end
            else if (~_GEN_83) begin
              if (_GEN_61) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (_GEN_62)
                state <= 5'hA;
              else if (_GEN_63)
                state <= _GEN_71;
              else if (_GEN_72)
                state <= _GEN_85;
            end
          end
          if (commandWrite | _GEN_37 | ~_GEN_82)
            sectorByte <= 10'h0;
        end
        if (~_GEN_5 | commandWrite) begin
        end
        else begin
          lowByte <= 8'h0;
          wordData <= 16'h0;
        end
      end
      else begin
        if (_GEN_110) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
                ready <= _GEN_84;
                attention <= _GEN_77;
              end
              if (_GEN_73) begin
              end
              else if (_GEN_47) begin
                if (~addressValid)
                  er1 <= _er1_T_1;
              end
              else if (~_GEN_51) begin
                if (_GEN_52)
                  er1 <= 16'h0;
                else if (~_GEN_60) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      er1 <= _er1_T_2;
                  end
                  else if (_GEN_62)
                    er1 <= _er1_T_3;
                  else if (_GEN_63) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (addressValid) begin
                            if (_GEN_65)
                              er1 <= _er1_T_8;
                          end
                          else
                            er1 <= _er1_T_7;
                        end
                        else
                          er1 <= _er1_T_6;
                      end
                    end
                    else
                      er1 <= _er1_T_4;
                  end
                  else if (_GEN_72) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (~addressValid)
                            er1 <= _er1_T_12;
                        end
                        else
                          er1 <= _er1_T_11;
                      end
                    end
                    else
                      er1 <= _er1_T_9;
                  end
                end
              end
            end
            else begin
              if (_GEN_95) begin
              end
              else
                cs2 <= _GEN_99;
              if (~_GEN_94) begin
                if (_GEN_92) begin
                  if (_merged_T_15[5])
                    er1 <= 16'h0;
                end
                else
                  er1 <= _GEN_101;
                attention <= _GEN_103;
              end
              ready <= _GEN_98;
            end
          end
        end
        else if (_GEN_9) begin
          if (_GEN_25)
            cs2 <= {cs2[15:12], _GEN_28};
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
              end
            end
            else if (_GEN_95) begin
            end
            else
              cs2 <= _GEN_99;
          end
          if (_GEN_25 | ~_GEN_40) begin
          end
          else if (_GEN_41) begin
            if (_GEN_73) begin
            end
            else if (_GEN_47) begin
              if (~addressValid)
                er1 <= _er1_T_1;
            end
            else if (~_GEN_51) begin
              if (_GEN_52)
                er1 <= 16'h0;
              else if (~_GEN_60) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    er1 <= _er1_T_2;
                end
                else if (_GEN_62)
                  er1 <= _er1_T_3;
                else if (_GEN_63) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (addressValid) begin
                          if (_GEN_65)
                            er1 <= _er1_T_8;
                        end
                        else
                          er1 <= _er1_T_7;
                      end
                      else
                        er1 <= _er1_T_6;
                    end
                  end
                  else
                    er1 <= _er1_T_4;
                end
                else if (_GEN_72) begin
                  if (io_block_initialized) begin
                    if (~(|(cs2[2:0]))) begin
                      if (volumeValid) begin
                        if (~addressValid)
                          er1 <= _er1_T_12;
                      end
                      else
                        er1 <= _er1_T_11;
                    end
                  end
                  else
                    er1 <= _er1_T_9;
                end
              end
            end
          end
          else if (~_GEN_94) begin
            if (_GEN_92) begin
              if (_merged_T_15[5])
                er1 <= 16'h0;
            end
            else
              er1 <= _GEN_101;
          end
          if (io_memory_responseValid) begin
            ready <= io_memory_responseError ? _GEN_5 | _GEN_120 : _GEN_24 | _GEN_120;
            attention <=
              io_memory_responseError ? _GEN_5 | _GEN_121 : ~_GEN_24 & _GEN_121;
          end
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                ready <= _GEN_84;
                attention <= _GEN_77;
              end
            end
            else begin
              ready <= _GEN_98;
              if (~_GEN_94)
                attention <= _GEN_103;
            end
          end
        end
        else if (_GEN_10) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
                ready <= _GEN_84;
                attention <= _GEN_77;
              end
              if (_GEN_73) begin
              end
              else if (_GEN_47) begin
                if (~addressValid)
                  er1 <= _er1_T_1;
              end
              else if (~_GEN_51) begin
                if (_GEN_52)
                  er1 <= 16'h0;
                else if (~_GEN_60) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      er1 <= _er1_T_2;
                  end
                  else if (_GEN_62)
                    er1 <= _er1_T_3;
                  else if (_GEN_63) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (addressValid) begin
                            if (_GEN_65)
                              er1 <= _er1_T_8;
                          end
                          else
                            er1 <= _er1_T_7;
                        end
                        else
                          er1 <= _er1_T_6;
                      end
                    end
                    else
                      er1 <= _er1_T_4;
                  end
                  else if (_GEN_72) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (~addressValid)
                            er1 <= _er1_T_12;
                        end
                        else
                          er1 <= _er1_T_11;
                      end
                    end
                    else
                      er1 <= _er1_T_9;
                  end
                end
              end
            end
            else begin
              if (_GEN_95) begin
              end
              else
                cs2 <= _GEN_99;
              if (~_GEN_94) begin
                if (_GEN_92) begin
                  if (_merged_T_15[5])
                    er1 <= 16'h0;
                end
                else
                  er1 <= _GEN_101;
                attention <= _GEN_103;
              end
              ready <= _GEN_98;
            end
          end
        end
        else if (_GEN_11) begin
          if (io_block_done) begin
            cs2 <= {cs2[15:12], _GEN_28};
            if (io_block_error)
              er1 <= {er1[15:14], _GEN_27};
          end
          else if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
              end
              if (_GEN_73) begin
              end
              else if (_GEN_47) begin
                if (~addressValid)
                  er1 <= _er1_T_1;
              end
              else if (~_GEN_51) begin
                if (_GEN_52)
                  er1 <= 16'h0;
                else if (~_GEN_60) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      er1 <= _er1_T_2;
                  end
                  else if (_GEN_62)
                    er1 <= _er1_T_3;
                  else if (_GEN_63) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (addressValid) begin
                            if (_GEN_65)
                              er1 <= _er1_T_8;
                          end
                          else
                            er1 <= _er1_T_7;
                        end
                        else
                          er1 <= _er1_T_6;
                      end
                    end
                    else
                      er1 <= _er1_T_4;
                  end
                  else if (_GEN_72) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (~addressValid)
                            er1 <= _er1_T_12;
                        end
                        else
                          er1 <= _er1_T_11;
                      end
                    end
                    else
                      er1 <= _er1_T_9;
                  end
                end
              end
            end
            else begin
              if (_GEN_95) begin
              end
              else
                cs2 <= _GEN_99;
              if (~_GEN_94) begin
                if (_GEN_92) begin
                  if (_merged_T_15[5])
                    er1 <= 16'h0;
                end
                else
                  er1 <= _GEN_101;
              end
            end
          end
          ready <= io_block_done | _GEN_120;
          attention <= io_block_done | _GEN_121;
        end
        else if (_GEN_109) begin
          if (_GEN_40) begin
            if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
                ready <= _GEN_84;
                attention <= _GEN_77;
              end
              if (_GEN_73) begin
              end
              else if (_GEN_47) begin
                if (~addressValid)
                  er1 <= _er1_T_1;
              end
              else if (~_GEN_51) begin
                if (_GEN_52)
                  er1 <= 16'h0;
                else if (~_GEN_60) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      er1 <= _er1_T_2;
                  end
                  else if (_GEN_62)
                    er1 <= _er1_T_3;
                  else if (_GEN_63) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (addressValid) begin
                            if (_GEN_65)
                              er1 <= _er1_T_8;
                          end
                          else
                            er1 <= _er1_T_7;
                        end
                        else
                          er1 <= _er1_T_6;
                      end
                    end
                    else
                      er1 <= _er1_T_4;
                  end
                  else if (_GEN_72) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (~addressValid)
                            er1 <= _er1_T_12;
                        end
                        else
                          er1 <= _er1_T_11;
                      end
                    end
                    else
                      er1 <= _er1_T_9;
                  end
                end
              end
            end
            else begin
              if (_GEN_95) begin
              end
              else
                cs2 <= _GEN_99;
              if (~_GEN_94) begin
                if (_GEN_92) begin
                  if (_merged_T_15[5])
                    er1 <= 16'h0;
                end
                else
                  er1 <= _GEN_101;
                attention <= _GEN_103;
              end
              ready <= _GEN_98;
            end
          end
        end
        else begin
          if (_GEN_17) begin
            if (_GEN_26)
              cs2 <= {cs2[15:12], _GEN_28};
            else if (_GEN_40) begin
              if (_GEN_41) begin
                if (_merged_T_7[0]) begin
                  if (|(cs2[2:0]))
                    cs2 <= _cs2_T;
                  else if (~_GEN_76) begin
                    if (_GEN_52)
                      cs2 <= _GEN_53;
                    else if (~_GEN_75) begin
                      if (_GEN_63) begin
                        if (_GEN_67)
                          cs2 <= _cs2_T_6;
                      end
                      else if (_GEN_74)
                        cs2 <= _cs2_T_11;
                    end
                  end
                end
              end
              else if (_GEN_95) begin
              end
              else
                cs2 <= _GEN_99;
            end
            if (_GEN_26 | ~_GEN_40) begin
            end
            else if (_GEN_41) begin
              if (_GEN_73) begin
              end
              else if (_GEN_47) begin
                if (~addressValid)
                  er1 <= _er1_T_1;
              end
              else if (~_GEN_51) begin
                if (_GEN_52)
                  er1 <= 16'h0;
                else if (~_GEN_60) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      er1 <= _er1_T_2;
                  end
                  else if (_GEN_62)
                    er1 <= _er1_T_3;
                  else if (_GEN_63) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (addressValid) begin
                            if (_GEN_65)
                              er1 <= _er1_T_8;
                          end
                          else
                            er1 <= _er1_T_7;
                        end
                        else
                          er1 <= _er1_T_6;
                      end
                    end
                    else
                      er1 <= _er1_T_4;
                  end
                  else if (_GEN_72) begin
                    if (io_block_initialized) begin
                      if (~(|(cs2[2:0]))) begin
                        if (volumeValid) begin
                          if (~addressValid)
                            er1 <= _er1_T_12;
                        end
                        else
                          er1 <= _er1_T_11;
                      end
                    end
                    else
                      er1 <= _er1_T_9;
                  end
                end
              end
            end
            else if (~_GEN_94) begin
              if (_GEN_92) begin
                if (_merged_T_15[5])
                  er1 <= 16'h0;
              end
              else
                er1 <= _GEN_101;
            end
            attention <= _GEN_26 | _GEN_121;
          end
          else begin
            if (_GEN_112) begin
              if (_GEN_40) begin
                if (_GEN_41) begin
                  if (_merged_T_7[0]) begin
                    if (|(cs2[2:0]))
                      cs2 <= _cs2_T;
                    else if (~_GEN_76) begin
                      if (_GEN_52)
                        cs2 <= _GEN_53;
                      else if (~_GEN_75) begin
                        if (_GEN_63) begin
                          if (_GEN_67)
                            cs2 <= _cs2_T_6;
                        end
                        else if (_GEN_74)
                          cs2 <= _cs2_T_11;
                      end
                    end
                  end
                end
                else if (_GEN_95) begin
                end
                else
                  cs2 <= _GEN_99;
              end
            end
            else if (_GEN_123 | ~_GEN_40) begin
            end
            else if (_GEN_41) begin
              if (_merged_T_7[0]) begin
                if (|(cs2[2:0]))
                  cs2 <= _cs2_T;
                else if (~_GEN_76) begin
                  if (_GEN_52)
                    cs2 <= _GEN_53;
                  else if (~_GEN_75) begin
                    if (_GEN_63) begin
                      if (_GEN_67)
                        cs2 <= _cs2_T_6;
                    end
                    else if (_GEN_74)
                      cs2 <= _cs2_T_11;
                  end
                end
              end
            end
            else if (_GEN_95) begin
            end
            else
              cs2 <= _GEN_99;
            if (_GEN_112 | ~_GEN_123) begin
              if (_GEN_40) begin
                if (_GEN_41) begin
                  if (_GEN_73) begin
                  end
                  else if (_GEN_47) begin
                    if (~addressValid)
                      er1 <= _er1_T_1;
                  end
                  else if (~_GEN_51) begin
                    if (_GEN_52)
                      er1 <= 16'h0;
                    else if (~_GEN_60) begin
                      if (_GEN_61) begin
                        if (~addressValid)
                          er1 <= _er1_T_2;
                      end
                      else if (_GEN_62)
                        er1 <= _er1_T_3;
                      else if (_GEN_63) begin
                        if (io_block_initialized) begin
                          if (~(|(cs2[2:0]))) begin
                            if (volumeValid) begin
                              if (addressValid) begin
                                if (_GEN_65)
                                  er1 <= _er1_T_8;
                              end
                              else
                                er1 <= _er1_T_7;
                            end
                            else
                              er1 <= _er1_T_6;
                          end
                        end
                        else
                          er1 <= _er1_T_4;
                      end
                      else if (_GEN_72) begin
                        if (io_block_initialized) begin
                          if (~(|(cs2[2:0]))) begin
                            if (volumeValid) begin
                              if (~addressValid)
                                er1 <= _er1_T_12;
                            end
                            else
                              er1 <= _er1_T_11;
                          end
                        end
                        else
                          er1 <= _er1_T_9;
                      end
                    end
                  end
                end
                else if (~_GEN_94) begin
                  if (_GEN_92) begin
                    if (_merged_T_15[5])
                      er1 <= 16'h0;
                  end
                  else
                    er1 <= _GEN_101;
                end
              end
            end
            else
              er1 <= {er1[15:14], _GEN_27};
            if (_GEN_114) begin
              if (_GEN_40) begin
                if (_GEN_41) begin
                  if (_merged_T_7[0])
                    attention <= _GEN_77;
                end
                else if (~_GEN_94)
                  attention <= _GEN_103;
              end
            end
            else
              attention <= io_block_error | ~_GEN_122 & _GEN_121;
          end
          ready <=
            _GEN_17
              ? _GEN_26 | _GEN_120
              : ~_GEN_112 & _GEN_111 & (io_block_error | _GEN_122) | _GEN_120;
        end
        if (_GEN_6) begin
          if (_GEN_35) begin
            state <= 5'h3;
            sectorByte <= sectorByte + 10'h1;
          end
          else begin
            if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_82) begin
            end
            else
              sectorByte <= 10'h0;
          end
        end
        else if (_GEN_7) begin
          if (_GEN_35) begin
            state <= 5'h4;
            wordData <= {io_block_read_bits, lowByte};
            sectorByte <= sectorByte + 10'h1;
          end
          else begin
            if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_82) begin
            end
            else
              sectorByte <= 10'h0;
          end
        end
        else if (_GEN_8) begin
          if (_GEN_34)
            state <= 5'h5;
          else if (_GEN_81) begin
            if (|(cs2[2:0]))
              state <= 5'hA;
            else if (_GEN_47) begin
              if (~addressValid)
                state <= 5'hA;
            end
            else if (~_GEN_83) begin
              if (_GEN_61) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (_GEN_62)
                state <= 5'hA;
              else if (_GEN_63)
                state <= _GEN_71;
              else if (_GEN_72)
                state <= _GEN_85;
            end
          end
          if (_GEN_82) begin
          end
          else
            sectorByte <= 10'h0;
        end
        else if (_GEN_9) begin
          if (io_memory_responseValid)
            state <=
              io_memory_responseError
                ? (_GEN_5 ? 5'hA : sectorByte == 10'h200 ? 5'h12 : 5'h11)
                : _GEN_5
                    ? ((&wc) ? 5'h0 : _GEN_108 ? 5'h1 : 5'h4)
                    : (&wc) ? 5'h6 : _GEN_33 ? 5'h9 : 5'h2;
          else if (_GEN_81) begin
            if (|(cs2[2:0]))
              state <= 5'hA;
            else if (_GEN_47) begin
              if (~addressValid)
                state <= 5'hA;
            end
            else if (~_GEN_83) begin
              if (_GEN_61) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (_GEN_62)
                state <= 5'hA;
              else if (_GEN_63)
                state <= _GEN_71;
              else if (_GEN_72)
                state <= _GEN_85;
            end
          end
          if (~io_memory_responseValid | io_memory_responseError | ~_GEN_5 | (&wc)
              | _GEN_108) begin
            if (_GEN_82) begin
            end
            else
              sectorByte <= 10'h0;
          end
          else begin
            wordData <= 16'h0;
            sectorByte <= sectorByte + 10'h2;
          end
        end
        else begin
          if (_GEN_10) begin
            if (_GEN_33)
              state <= 5'h12;
            else if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_36) begin
              if (_GEN_82) begin
              end
              else
                sectorByte <= 10'h0;
            end
            else
              sectorByte <= sectorByte + 10'h1;
          end
          else if (_GEN_11) begin
            if (io_block_done)
              state <= 5'hA;
            else if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_82) begin
            end
            else
              sectorByte <= 10'h0;
          end
          else if (_GEN_12) begin
            if (_GEN_33)
              state <= 5'h9;
            else if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_36) begin
              if (_GEN_82) begin
              end
              else
                sectorByte <= 10'h0;
            end
            else
              sectorByte <= sectorByte + 10'h1;
          end
          else begin
            if (_GEN_15) begin
              if (_GEN_34)
                state <= 5'h8;
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (_GEN_17) begin
              if (io_memory_responseValid)
                state <= io_memory_responseError ? 5'hA : 5'hD;
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (_GEN)
              state <= 5'hE;
            else if (_GEN_0)
              state <= _GEN_29 ? 5'hF : _GEN_31 ? 5'h10 : 5'h7;
            else if (_GEN_1) begin
              if (_GEN_30)
                state <= 5'h10;
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (_io_block_request_bits_write_T) begin
              if (_GEN_37)
                state <= 5'hC;
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (_GEN_18) begin
              if (_GEN_32)
                state <= _GEN_30 ? 5'h9 : 5'hC;
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (_partialSectorRead_T_1)
              state <= 5'hB;
            else if (_GEN_111) begin
              if (io_block_error)
                state <= 5'hA;
              else if (io_block_done)
                state <= {4'h0, ~_GEN_113};
              else if (_GEN_81) begin
                if (|(cs2[2:0]))
                  state <= 5'hA;
                else if (_GEN_47) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (~_GEN_83) begin
                  if (_GEN_61) begin
                    if (~addressValid)
                      state <= 5'hA;
                  end
                  else if (_GEN_62)
                    state <= 5'hA;
                  else if (_GEN_63)
                    state <= _GEN_71;
                  else if (_GEN_72)
                    state <= _GEN_85;
                end
              end
            end
            else if (state == 5'hA)
              state <= 5'h0;
            else if (_GEN_81) begin
              if (|(cs2[2:0]))
                state <= 5'hA;
              else if (_GEN_47) begin
                if (~addressValid)
                  state <= 5'hA;
              end
              else if (~_GEN_83) begin
                if (_GEN_61) begin
                  if (~addressValid)
                    state <= 5'hA;
                end
                else if (_GEN_62)
                  state <= 5'hA;
                else if (_GEN_63)
                  state <= _GEN_71;
                else if (_GEN_72)
                  state <= _GEN_85;
              end
            end
            if (_GEN_15 | _GEN_17) begin
              if (_GEN_82) begin
              end
              else
                sectorByte <= 10'h0;
            end
            else if (_GEN)
              sectorByte <= sectorByte + 10'h1;
            else if (_GEN_0)
              sectorByte <=
                _GEN_29 ? sectorByte + 10'h1 : _GEN_31 ? 10'h0 : sectorByte + 10'h1;
            else if (_GEN_1)
              sectorByte <= _GEN_30 ? 10'h0 : sectorByte + 10'h1;
            else if (_io_block_request_bits_write_T) begin
              if (_GEN_37 | ~_GEN_82)
                sectorByte <= 10'h0;
            end
            else if (_GEN_18) begin
              if (~_GEN_32 | _GEN_30) begin
                if (_GEN_82) begin
                end
                else
                  sectorByte <= 10'h0;
              end
              else
                sectorByte <= sectorByte + 10'h1;
            end
            else if ((_partialSectorRead_T_1 | ~_GEN_111 | io_block_error | ~io_block_done
                      | _GEN_113) & _GEN_82) begin
            end
            else
              sectorByte <= 10'h0;
          end
          if (_GEN_10 | _GEN_11 | _GEN_109 | ~(_GEN_17 & io_memory_responseValid)
              | io_memory_responseError) begin
          end
          else
            wordData <= io_memory_responseData;
        end
        if (_GEN_6 & _GEN_35)
          lowByte <= io_block_read_bits;
      end
      if (_GEN_40) begin
        if (_GEN_41) begin
          if (~(_merged_T_7[0]) | _GEN_124 | ~_GEN_54) begin
          end
          else
            of <= 16'h1000;
          function_0 <= _merged_T_7[5:1];
        end
        else begin
          if (_GEN_86 | _GEN_88 | _GEN_90 | _GEN_92 | _GEN_100 | _GEN_102
              | ~_GEN_104) begin
          end
          else
            of <=
              {io_bus_byteEnable[1] ? io_bus_dataIn[15:8] : of[15:8],
               io_bus_byteEnable[0] ? io_bus_dataIn[7:0] : of[7:0]};
          if (_GEN_125) begin
          end
          else
            function_0 <= 5'h0;
        end
        volumeValid <=
          _GEN_41
            ? _merged_T_7[0] & ~_GEN_124 & _GEN_60 | volumeValid
            : _GEN_125 & volumeValid;
      end
      ie <=
        _GEN_40
          ? (_GEN_41 ? _merged_T_7[6] : _GEN_95 ? _GEN_39 : ~_GEN_93 & ie)
          : _GEN_39;
      pending <=
        _GEN_3
          ? _GEN_96
          : _GEN_4
              ? _GEN_5 & commandWrite & _GEN_45 | _GEN_96
              : _GEN_110
                  ? _GEN_96
                  : _GEN_9
                      ? (io_memory_responseValid
                           ? (io_memory_responseError
                                ? _GEN_5 & _GEN_45 | _GEN_96
                                : _GEN_5 & (&wc) & ie | _GEN_96)
                           : _GEN_96)
                      : _GEN_10
                          ? _GEN_96
                          : _GEN_11
                              ? io_block_done & _GEN_45 | _GEN_96
                              : _GEN_109
                                  ? _GEN_96
                                  : _GEN_17
                                      ? io_memory_responseValid & io_memory_responseError
                                        & _GEN_45 | _GEN_96
                                      : _GEN_114
                                          ? _GEN_96
                                          : io_block_error
                                              ? _GEN_45 | _GEN_96
                                              : io_block_done & _GEN_113 & ie | _GEN_96;
      if (~_GEN_81 | _GEN_80) begin
      end
      else
        commandWrite <= _GEN_63 ? ~_GEN_69 | commandWrite : _GEN_79 & commandWrite;
    end
  end // always @(posedge)
  partialSector_512x8 partialSector_ext (
    .R0_addr (sectorByte[8:0]),
    .R0_en   (_partialSectorRead_T_1),
    .R0_clk  (clock),
    .R0_data (_partialSector_ext_R0_data),
    .W0_addr (sectorByte[8:0]),
    .W0_en   (_GEN | _GEN_0 | _GEN_1),
    .W0_clk  (clock),
    .W0_data (_GEN ? wordData[7:0] : _GEN_0 ? wordData[15:8] : 8'h0)
  );
  assign io_bus_hit = wordAddress > 22'h3FFDBF & wordAddress < 22'h3FFDEB;
  assign io_bus_dataOut =
    _offset_T == 22'h2A
      ? 16'h0
      : _offset_T == 22'h28
          ? {10'h0, bae}
          : _offset_T == 22'h1E | _offset_T == 22'h1C
              ? dc
              : _offset_T == 22'h1A
                  ? of
                  : _offset_T == 22'h18
                      ? {15'h0, ~(|(cs2[2:0]))}
                      : _offset_T == 22'h16
                          ? {2'h0, (|(cs2[2:0])) ? 14'h0 : 14'h2012}
                          : _offset_T == 22'h14 | _offset_T == 22'h12
                            | _offset_T == 22'h10
                              ? 16'h0
                              : _offset_T == 22'hE
                                  ? {15'h0, attention}
                                  : _offset_T == 22'hC
                                      ? er1
                                      : _offset_T == 22'hA
                                          ? ((|(cs2[2:0]))
                                               ? 16'h0
                                               : {attention,
                                                  |_GEN_2,
                                                  1'h0,
                                                  io_block_initialized,
                                                  4'h1,
                                                  ready,
                                                  volumeValid,
                                                  6'h0})
                                          : _offset_T == 22'h8
                                              ? cs2
                                              : _offset_T == 22'h6
                                                  ? da
                                                  : _offset_T == 22'h4
                                                      ? ba
                                                      : _offset_T == 22'h2
                                                          ? wc
                                                          : _offset_T == 22'h0
                                                              ? {specialCondition,
                                                                 |_GEN_2,
                                                                 2'h0,
                                                                 ~(|(cs2[2:0])),
                                                                 1'h0,
                                                                 bae[1:0],
                                                                 ready,
                                                                 ie,
                                                                 function_0,
                                                                 busy_layerCapture}
                                                              : 16'h0;
  assign io_memory_request_valid = io_memory_request_valid_0;
  assign io_memory_request_bits_write = ~_GEN_16 & _GEN_8;
  assign io_memory_request_bits_address = {bae, ba};
  assign io_memory_request_bits_data = wordData;
  assign io_block_request_valid = io_block_request_valid_0;
  assign io_block_request_bits_write = commandWrite & _io_block_request_bits_write_T;
  assign io_block_request_bits_lba = lba;
  assign io_block_read_ready = io_block_read_ready_0;
  assign io_block_write_valid = io_block_write_valid_0;
  assign io_block_write_bits =
    _GEN_3 | _GEN_4 | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12
    | _GEN_15 | _GEN_17 | _GEN | _GEN_0 | _GEN_1 | _io_block_request_bits_write_T
    | ~_GEN_18
      ? 8'h0
      : _partialSector_ext_R0_data;
  assign io_irq = pending | specialCondition & ready & ie;
endmodule

