// Generated by CIRCT firtool-1.149.0
module SdBlockDevice(
  input         clock,
                reset,
  output        io_block_request_ready,
  input         io_block_request_valid,
                io_block_request_bits_write,
  input  [31:0] io_block_request_bits_lba,
  input         io_block_read_ready,
  output        io_block_read_valid,
  output [7:0]  io_block_read_bits,
  output        io_block_write_ready,
  input         io_block_write_valid,
  input  [7:0]  io_block_write_bits,
  output        io_block_done,
                io_block_error,
                io_block_initialized,
  input         io_miso,
  output        io_sck,
                io_mosi,
                io_csN,
                io_active
);

  wire        spiStart;
  wire        _GEN;
  wire        _GEN_0;
  reg         spiFast;
  reg         spiBusy;
  reg         spiSck;
  reg         spiMosi;
  reg  [5:0]  spiTimer;
  reg  [2:0]  spiBit;
  reg  [7:0]  spiTxShift;
  reg  [7:0]  spiRxShift;
  reg         misoMeta;
  reg         misoSync;
  wire        _GEN_1;
  wire        _GEN_2;
  wire        _GEN_3;
  wire        _GEN_4;
  wire        spiDone;
  reg  [3:0]  commandState;
  reg  [5:0]  commandNumberReg;
  reg  [31:0] commandArgumentReg;
  reg  [7:0]  commandCrcReg;
  reg  [2:0]  commandExtraCountReg;
  reg         commandPostClockReg;
  reg  [2:0]  commandIndex;
  reg  [6:0]  commandTries;
  reg  [2:0]  commandExtraIndex;
  reg  [7:0]  commandResponse;
  reg  [7:0]  commandExtra_0;
  reg  [7:0]  commandExtra_1;
  reg  [7:0]  commandExtra_2;
  reg  [7:0]  commandExtra_3;
  reg  [7:0]  casez_tmp;
  wire        _GEN_5;
  wire        _GEN_6;
  wire        _GEN_7;
  wire        _GEN_8;
  wire        _GEN_9;
  wire        _GEN_10;
  wire        _GEN_11;
  wire        _GEN_12;
  wire        _GEN_13;
  wire        _GEN_14;
  wire        _GEN_15;
  wire        _GEN_16;
  wire        _GEN_17;
  wire        _GEN_18;
  wire        _GEN_19;
  wire        _GEN_20;
  wire [7:0]  _GEN_21;
  wire        _GEN_22;
  wire        _GEN_23;
  wire        commandDone;
  wire        commandFailed;
  reg  [3:0]  casez_tmp_0;
  reg  [5:0]  state;
  reg         csN;
  reg         initialized;
  reg         failed;
  reg         sdhc;
  reg         version2;
  reg  [3:0]  trainCount;
  reg  [13:0] acmdCount;
  reg  [15:0] tokenCount;
  reg  [9:0]  byteIndex;
  reg         crcIndex;
  reg  [15:0] readCrc;
  reg  [7:0]  readCrcHigh;
  reg  [15:0] writeCrc;
  reg  [31:0] requestLba;
  reg  [23:0] initWait;
  reg         readValid;
  reg  [7:0]  readData;
  reg         done;
  reg         operationError;
  wire        _io_block_request_ready_T;
  wire        io_block_request_ready_0;
  wire        _io_block_write_ready_T;
  wire        io_block_write_ready_0;
  wire        _GEN_24;
  wire        _GEN_25;
  wire        _GEN_26;
  wire        _GEN_27;
  wire        _GEN_28;
  wire [7:0]  _GEN_29;
  wire        _GEN_30;
  wire        _GEN_31;
  wire        _GEN_32;
  wire        _GEN_33;
  wire        _GEN_34;
  wire        _GEN_35;
  wire        _GEN_36;
  wire        _GEN_37;
  wire        _GEN_38;
  wire        _GEN_39;
  wire        _GEN_40;
  wire        _GEN_41;
  wire        _GEN_42;
  wire        _GEN_43;
  wire        _GEN_44;
  wire        _GEN_45;
  wire        _GEN_46;
  wire        _GEN_47;
  wire        _GEN_48;
  wire        _GEN_49;
  wire        _GEN_50;
  wire        _GEN_51;
  wire        _GEN_52;
  wire        _GEN_53;
  wire        _GEN_54;
  wire        _GEN_55;
  wire        _GEN_56;
  wire        _GEN_57;
  wire        _GEN_58;
  wire [31:0] _GEN_59;
  wire        _GEN_60;
  wire        _GEN_61;
  wire        _GEN_62;
  wire        _GEN_63;
  wire        _GEN_64;
  wire        _GEN_65;
  wire        _GEN_66;
  wire        _GEN_67;
  wire        _GEN_68;
  wire        _GEN_69;
  wire        _GEN_70;
  wire        _GEN_71;
  wire        _GEN_72;
  wire        _GEN_73;
  wire        _GEN_74;
  wire        _GEN_75;
  wire        _GEN_76;
  wire        _GEN_77;
  wire [5:0]  commandNumber;
  wire [31:0] commandArgument;
  wire        _GEN_78;
  wire        _GEN_79;
  wire        _GEN_80;
  wire        _GEN_81;
  wire        _GEN_82;
  wire        _GEN_83;
  wire        _GEN_84;
  wire        _GEN_85;
  wire        _GEN_86;
  wire        _GEN_87;
  wire        _GEN_88;
  wire        _GEN_89;
  wire        _GEN_90;
  wire        _GEN_91;
  wire        _GEN_92;
  wire        _GEN_93;
  wire        _GEN_94;
  wire [7:0]  spiTx;
  wire        _GEN_95;
  wire        _GEN_96;
  wire        _GEN_97;
  wire        _GEN_98;
  wire        _GEN_99;
  wire        _GEN_100;
  wire        _GEN_101;
  wire        _GEN_102;
  wire        _GEN_103;
  wire        _GEN_104;
  reg  [3:0]  casez_tmp_1;
  wire [3:0]  _GEN_105;
  reg  [5:0]  casez_tmp_2;
  wire [5:0]  _GEN_106;
  wire [5:0]  _GEN_107;
  wire [5:0]  _GEN_108;
  reg  [23:0] casez_tmp_3;
  wire [23:0] _GEN_109;
  wire [23:0] _GEN_110;
  wire [23:0] _GEN_111;
  wire        _GEN_112;
  wire        _GEN_113;
  wire        _GEN_114;
  wire        _GEN_115;
  wire        _GEN_116;
  wire [15:0] _readCrc_T_3;
  wire [15:0] _readCrc_T_7;
  wire [15:0] _readCrc_T_11;
  wire [15:0] _readCrc_T_15;
  wire [15:0] _readCrc_T_19;
  wire [15:0] _readCrc_T_23;
  wire [15:0] _readCrc_T_27;
  wire [15:0] _writeCrc_T_3;
  wire [15:0] _writeCrc_T_7;
  wire [15:0] _writeCrc_T_11;
  wire [15:0] _writeCrc_T_15;
  wire [15:0] _writeCrc_T_19;
  wire [15:0] _writeCrc_T_23;
  wire [15:0] _writeCrc_T_27;
  wire        _GEN_117;
  wire [5:0]  halfTicks;
  wire        _GEN_118;
  wire        _GEN_119;
  wire        _GEN_120;
  wire        _GEN_121;
  wire        _GEN_122;
  wire        _GEN_123;
  wire        _GEN_124;
  wire        _GEN_125;
  wire        _GEN_126;
  wire        _GEN_127;
  wire        _GEN_128;
  wire        _GEN_129;
  wire        _GEN_130;
  wire        _GEN_131;
  wire        _GEN_132;
  wire        _GEN_133;
  wire        _GEN_134;
  wire        _GEN_135;
  wire        _GEN_136;
  wire        _GEN_137;
  wire [6:0]  _commandCrcReg_T_10;
  wire [6:0]  _commandCrcReg_T_15;
  wire [6:0]  _commandCrcReg_T_19;
  wire [6:0]  _commandCrcReg_T_23;
  wire [6:0]  _commandCrcReg_T_27;
  wire [6:0]  _commandCrcReg_T_31;
  wire [6:0]  _commandCrcReg_T_36;
  wire [6:0]  _commandCrcReg_T_40;
  wire [6:0]  _commandCrcReg_T_44;
  wire [6:0]  _commandCrcReg_T_48;
  wire [6:0]  _commandCrcReg_T_52;
  wire [6:0]  _commandCrcReg_T_56;
  wire [6:0]  _commandCrcReg_T_60;
  wire [6:0]  _commandCrcReg_T_64;
  wire [6:0]  _commandCrcReg_T_69;
  wire [6:0]  _commandCrcReg_T_73;
  wire [6:0]  _commandCrcReg_T_77;
  wire [6:0]  _commandCrcReg_T_81;
  wire [6:0]  _commandCrcReg_T_85;
  wire [6:0]  _commandCrcReg_T_89;
  wire [6:0]  _commandCrcReg_T_93;
  wire [6:0]  _commandCrcReg_T_97;
  wire [6:0]  _commandCrcReg_T_102;
  wire [6:0]  _commandCrcReg_T_106;
  wire [6:0]  _commandCrcReg_T_110;
  wire [6:0]  _commandCrcReg_T_114;
  wire [6:0]  _commandCrcReg_T_118;
  wire [6:0]  _commandCrcReg_T_122;
  wire [6:0]  _commandCrcReg_T_126;
  wire [6:0]  _commandCrcReg_T_130;
  wire [6:0]  _commandCrcReg_T_135;
  wire [6:0]  _commandCrcReg_T_139;
  wire [6:0]  _commandCrcReg_T_143;
  wire [6:0]  _commandCrcReg_T_147;
  wire [6:0]  _commandCrcReg_T_151;
  wire [6:0]  _commandCrcReg_T_155;
  wire [6:0]  _commandCrcReg_T_159;
  assign _GEN_1 = spiStart & ~spiBusy;
  assign _GEN_2 = spiTimer == 6'h0;
  assign _GEN_3 = spiBusy & _GEN_2;
  assign _GEN_4 = spiBit == 3'h0;
  assign spiDone = ~_GEN_1 & _GEN_3 & spiSck & _GEN_4;
  always_comb begin
    casez (commandIndex)
      3'b000:
        casez_tmp = {2'h1, commandNumberReg};
      3'b001:
        casez_tmp = commandArgumentReg[31:24];
      3'b010:
        casez_tmp = commandArgumentReg[23:16];
      3'b011:
        casez_tmp = commandArgumentReg[15:8];
      3'b100:
        casez_tmp = commandArgumentReg[7:0];
      3'b101:
        casez_tmp = commandCrcReg;
      3'b110:
        casez_tmp = commandCrcReg;
      default:
        casez_tmp = commandCrcReg;
    endcase
  end // always_comb
  assign _GEN_5 = commandState == 4'h0;
  assign _GEN_6 = _GEN & _GEN_0 & _GEN_5;
  assign _GEN_7 = commandState == 4'h1;
  assign _GEN_8 = commandState == 4'h2;
  assign _GEN_9 = commandIndex == 3'h5;
  assign _GEN_10 = commandState == 4'h3;
  assign _GEN_11 = commandState == 4'h4;
  assign _GEN_12 = commandExtraCountReg == 3'h0;
  assign _GEN_13 = commandTries == 7'h3F;
  assign _GEN_14 = commandState == 4'h5;
  assign _GEN_15 = commandState == 4'h6;
  assign _GEN_16 = commandExtraIndex == commandExtraCountReg - 3'h1;
  assign _GEN_17 = commandState == 4'h7;
  assign _GEN_18 =
    ~_GEN_6 & (_GEN_7 | ~_GEN_8 & (_GEN_10 | ~_GEN_11 & (_GEN_14 | ~_GEN_15 & _GEN_17)))
    & ~spiBusy;
  assign _GEN_19 = _GEN_7 & ~spiBusy;
  assign _GEN_20 = _GEN_6 | ~_GEN_19;
  assign _GEN_21 = _GEN_20 ? 8'hFF : casez_tmp;
  assign _GEN_22 = commandState == 4'h8;
  assign _GEN_23 = commandState == 4'h9;
  assign commandDone =
    ~(_GEN_6 | _GEN_7 | _GEN_8 | _GEN_10 | _GEN_11 | _GEN_14 | _GEN_15 | _GEN_17
      | _GEN_22) & _GEN_23;
  assign commandFailed =
    ~(_GEN_6 | _GEN_7 | _GEN_8 | _GEN_10 | _GEN_11 | _GEN_14 | _GEN_15 | _GEN_17 | _GEN_22
      | _GEN_23) & commandState == 4'hA;
  always_comb begin
    casez (commandState)
      4'b0000:
        casez_tmp_0 = commandState;
      4'b0001:
        casez_tmp_0 = spiBusy ? commandState : 4'h2;
      4'b0010:
        casez_tmp_0 = spiDone ? {2'h0, _GEN_9, 1'h1} : commandState;
      4'b0011:
        casez_tmp_0 = spiBusy ? commandState : 4'h4;
      4'b0100:
        casez_tmp_0 =
          spiDone
            ? (spiRxShift[7]
                 ? (_GEN_13 ? 4'hA : 4'h3)
                 : _GEN_12 ? (commandPostClockReg ? 4'h7 : 4'h9) : 4'h5)
            : commandState;
      4'b0101:
        casez_tmp_0 = spiBusy ? commandState : 4'h6;
      4'b0110:
        casez_tmp_0 =
          spiDone ? (_GEN_16 ? (commandPostClockReg ? 4'h7 : 4'h9) : 4'h5) : commandState;
      4'b0111:
        casez_tmp_0 = spiBusy ? commandState : 4'h8;
      4'b1000:
        casez_tmp_0 = spiDone ? 4'h9 : commandState;
      4'b1001:
        casez_tmp_0 = 4'h0;
      4'b1010:
        casez_tmp_0 = 4'h0;
      4'b1011:
        casez_tmp_0 = commandState;
      4'b1100:
        casez_tmp_0 = commandState;
      4'b1101:
        casez_tmp_0 = commandState;
      4'b1110:
        casez_tmp_0 = commandState;
      default:
        casez_tmp_0 = commandState;
    endcase
  end // always_comb
  assign _io_block_request_ready_T = state == 6'hE;
  assign io_block_request_ready_0 = _io_block_request_ready_T & initialized;
  assign _io_block_write_ready_T = state == 6'h1C;
  assign io_block_write_ready_0 = _io_block_write_ready_T & ~spiBusy;
  assign _GEN_24 = state == 6'h0;
  assign _GEN_25 = initWait == 24'h7A11F;
  assign _GEN_26 = state == 6'h1;
  assign _GEN_27 = ~spiBusy | _GEN_18;
  assign _GEN_28 = ~spiBusy | _GEN_6 | ~_GEN_19;
  assign _GEN_29 = _GEN_28 ? 8'hFF : casez_tmp;
  assign _GEN_30 = trainCount == 4'h9;
  assign _GEN_31 = state == 6'h2;
  assign _GEN_32 = state == 6'h3;
  assign _GEN_33 = commandResponse != 8'h1;
  assign _GEN_34 = commandFailed | commandDone & _GEN_33;
  assign _GEN_35 = state == 6'h4;
  assign _GEN_36 = state == 6'h5;
  assign _GEN_37 = commandDone & commandResponse == 8'h1;
  assign _GEN_38 =
    (|{commandExtra_0, commandExtra_1}) | commandExtra_2 != 8'h1
    | commandExtra_3 != 8'hAA;
  assign _GEN_39 = commandDone & commandResponse == 8'h5;
  assign _GEN_40 = _GEN_39 | ~commandDone;
  assign _GEN_41 = state == 6'h28;
  assign _GEN_42 = state == 6'h29;
  assign _GEN_43 = state == 6'h6;
  assign _GEN_44 = state == 6'h7;
  assign _GEN_45 = commandDone & (|commandResponse);
  assign _GEN_46 = commandFailed | _GEN_45 & _GEN_33;
  assign _GEN_47 = state == 6'h8;
  assign _GEN_48 = state == 6'h9;
  assign _GEN_49 = commandDone & ~(|commandResponse);
  assign _GEN_50 = commandDone & acmdCount == 14'h1FFF;
  assign _GEN_51 = _GEN_49 | ~_GEN_50;
  assign _GEN_52 = state == 6'hA;
  assign _GEN_53 = state == 6'hB;
  assign _GEN_54 = commandFailed | _GEN_45;
  assign _GEN_55 = state == 6'hC;
  assign _GEN_56 = state == 6'hD;
  assign _GEN_57 = io_block_request_ready_0 & io_block_request_valid;
  assign _GEN_58 = state == 6'hF;
  assign _GEN_59 = sdhc ? requestLba : {requestLba[22:0], 9'h0};
  assign _GEN_60 = state == 6'h10;
  assign _GEN_61 = state == 6'h11;
  assign _GEN_62 = state == 6'h12;
  assign _GEN_63 = spiDone & spiRxShift == 8'hFE;
  assign _GEN_64 = spiDone & tokenCount == 16'hFFFE;
  assign _GEN_65 = state == 6'h13;
  assign _GEN_66 = state == 6'h14;
  assign _GEN_67 = state == 6'h15;
  assign _GEN_68 = io_block_read_ready & readValid;
  assign _GEN_69 = byteIndex == 10'h1FF;
  assign _GEN_70 = state == 6'h16;
  assign _GEN_71 = state == 6'h17;
  assign _GEN_72 = state == 6'h18;
  assign _GEN_73 =
    _GEN_60 | _GEN_61 | _GEN_62 | _GEN_65 | _GEN_66 | _GEN_67 | _GEN_70 | _GEN_71;
  assign _GEN_74 = _GEN_73 | ~(_GEN_72 & _GEN_5);
  assign _GEN_75 = _GEN_56 | _io_block_request_ready_T;
  assign _GEN_76 = _GEN_24 | _GEN_26;
  assign _GEN_77 = _GEN_76 | _GEN_31 | _GEN_32;
  assign commandNumber =
    _GEN_77
      ? 6'h0
      : _GEN_35
          ? {2'h0, _GEN_5, 3'h0}
          : _GEN_36
              ? 6'h0
              : _GEN_41
                  ? (_GEN_5 ? 6'h3B : 6'h0)
                  : _GEN_42
                      ? 6'h0
                      : _GEN_43
                          ? (_GEN_5 ? 6'h37 : 6'h0)
                          : _GEN_44
                              ? 6'h0
                              : _GEN_47
                                  ? (_GEN_5 ? 6'h29 : 6'h0)
                                  : _GEN_48
                                      ? 6'h0
                                      : _GEN_52
                                          ? (_GEN_5 ? 6'h3A : 6'h0)
                                          : _GEN_53
                                              ? 6'h0
                                              : _GEN_55
                                                  ? {1'h0, _GEN_5, 4'h0}
                                                  : _GEN_75
                                                      ? 6'h0
                                                      : _GEN_58
                                                          ? (_GEN_5 ? 6'h11 : 6'h0)
                                                          : _GEN_74 ? 6'h0 : 6'h18;
  assign commandArgument =
    _GEN_77
      ? 32'h0
      : _GEN_35
          ? (_GEN_5 ? 32'h1AA : 32'h0)
          : _GEN_36
              ? 32'h0
              : _GEN_41
                  ? {31'h0, _GEN_5}
                  : _GEN_42 | _GEN_43 | _GEN_44
                      ? 32'h0
                      : _GEN_47
                          ? (_GEN_5 ? {1'h0, version2, 30'h0} : 32'h0)
                          : _GEN_48 | _GEN_52 | _GEN_53
                              ? 32'h0
                              : _GEN_55
                                  ? {22'h0, _GEN_5, 9'h0}
                                  : _GEN_75
                                      ? 32'h0
                                      : _GEN_58
                                          ? (_GEN_5 ? _GEN_59 : 32'h0)
                                          : _GEN_74 ? 32'h0 : _GEN_59;
  assign _GEN_0 =
    _GEN_31 | ~_GEN_32
    & (_GEN_35 | ~_GEN_36
       & (_GEN_41 | ~_GEN_42
          & (_GEN_43 | ~_GEN_44
             & (_GEN_47 | ~_GEN_48
                & (_GEN_52 | ~_GEN_53
                   & (_GEN_55 | ~_GEN_75 & (_GEN_58 | ~_GEN_73 & _GEN_72)))))));
  assign _GEN = ~_GEN_76;
  assign _GEN_78 = state == 6'h19;
  assign _GEN_79 = state == 6'h1A;
  assign _GEN_80 = state == 6'h1B;
  assign _GEN_81 = io_block_write_ready_0 & io_block_write_valid;
  assign _GEN_82 = state == 6'h1D;
  assign _GEN_83 = state == 6'h1E;
  assign _GEN_84 = state == 6'h1F;
  assign _GEN_85 = state == 6'h20;
  assign _GEN_86 = state == 6'h21;
  assign _GEN_87 = spiDone & spiRxShift[4:0] != 5'h5;
  assign _GEN_88 = state == 6'h22;
  assign _GEN_89 = state == 6'h23;
  assign _GEN_90 = spiDone & (&spiRxShift);
  assign _GEN_91 = state == 6'h26;
  assign _GEN_92 = _GEN_71 | _GEN_72 | _GEN_78;
  assign _GEN_93 = _GEN_66 | _GEN_67;
  assign _GEN_94 =
    _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44
    | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55 | _GEN_56
    | _io_block_request_ready_T | _GEN_58 | _GEN_60;
  assign spiStart =
    _GEN_24
      ? _GEN_18
      : _GEN_26
          ? _GEN_27
          : _GEN_94
              ? _GEN_18
              : _GEN_61
                  ? _GEN_27
                  : _GEN_62
                      ? _GEN_18
                      : _GEN_65
                          ? _GEN_27
                          : _GEN_93
                              ? _GEN_18
                              : _GEN_70
                                  ? _GEN_27
                                  : _GEN_92
                                      ? _GEN_18
                                      : _GEN_79
                                          ? _GEN_27
                                          : _GEN_80
                                              ? _GEN_18
                                              : _io_block_write_ready_T
                                                  ? _GEN_81 | _GEN_18
                                                  : _GEN_82
                                                      ? _GEN_18
                                                      : _GEN_83
                                                          ? _GEN_27
                                                          : _GEN_84
                                                              ? _GEN_18
                                                              : _GEN_85
                                                                  ? _GEN_27
                                                                  : _GEN_86
                                                                      ? _GEN_18
                                                                      : _GEN_88
                                                                          ? _GEN_27
                                                                          : ~_GEN_89
                                                                            & _GEN_91
                                                                            & ~spiBusy
                                                                            | _GEN_18;
  assign spiTx =
    _GEN_24
      ? _GEN_21
      : _GEN_26
          ? _GEN_29
          : _GEN_94
              ? _GEN_21
              : _GEN_61
                  ? _GEN_29
                  : _GEN_62
                      ? _GEN_21
                      : _GEN_65
                          ? _GEN_29
                          : _GEN_93
                              ? _GEN_21
                              : _GEN_70
                                  ? _GEN_29
                                  : _GEN_92
                                      ? _GEN_21
                                      : _GEN_79
                                          ? (spiBusy ? _GEN_21 : 8'hFE)
                                          : _GEN_80
                                              ? _GEN_21
                                              : _io_block_write_ready_T
                                                  ? (_GEN_81
                                                       ? io_block_write_bits
                                                       : _GEN_21)
                                                  : _GEN_82
                                                      ? _GEN_21
                                                      : _GEN_83
                                                          ? (spiBusy
                                                               ? _GEN_21
                                                               : crcIndex
                                                                   ? writeCrc[7:0]
                                                                   : writeCrc[15:8])
                                                          : (_GEN_84
                                                             | ~(_GEN_85
                                                                 | ~(_GEN_86
                                                                     | ~(_GEN_88
                                                                         | ~(_GEN_89
                                                                             | ~_GEN_91))))
                                                               ? _GEN_20
                                                               : _GEN_28)
                                                              ? 8'hFF
                                                              : casez_tmp;
  assign _GEN_95 = state == 6'h27;
  assign _GEN_96 = state == 6'h24;
  assign _GEN_97 = state == 6'h25;
  assign _GEN_98 = initWait == 24'hBEBC1F;
  assign _GEN_99 = _GEN_97 & _GEN_98;
  assign _GEN_100 = _GEN_91 | _GEN_95 | _GEN_96;
  assign _GEN_101 =
    _io_block_request_ready_T | _GEN_58 | _GEN_60 | _GEN_61 | _GEN_62 | _GEN_65 | _GEN_66
    | _GEN_67 | _GEN_70 | _GEN_71 | _GEN_72 | _GEN_78 | _GEN_79 | _GEN_80
    | _io_block_write_ready_T | _GEN_82 | _GEN_83 | _GEN_84 | _GEN_85 | _GEN_86 | _GEN_88
    | _GEN_89 | _GEN_100;
  assign _GEN_102 = _GEN_55 | _GEN_56 | _GEN_101;
  assign _GEN_103 = _GEN_52 | _GEN_53 | _GEN_102;
  assign _GEN_104 = _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_103;
  assign _GEN_105 =
    _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_104 | ~_GEN_99 ? trainCount : 4'h0;
  always_comb begin
    casez (state)
      6'b000000:
        casez_tmp_1 = _GEN_25 ? 4'h0 : trainCount;
      6'b000001:
        casez_tmp_1 = spiDone ? (_GEN_30 ? 4'h0 : trainCount + 4'h1) : trainCount;
      6'b000010:
        casez_tmp_1 = trainCount;
      6'b000011:
        casez_tmp_1 = trainCount;
      6'b000100:
        casez_tmp_1 = trainCount;
      6'b000101:
        casez_tmp_1 = trainCount;
      6'b000110:
        casez_tmp_1 = trainCount;
      6'b000111:
        casez_tmp_1 = trainCount;
      6'b001000:
        casez_tmp_1 = trainCount;
      6'b001001:
        casez_tmp_1 = trainCount;
      6'b001010:
        casez_tmp_1 = trainCount;
      6'b001011:
        casez_tmp_1 = trainCount;
      6'b001100:
        casez_tmp_1 = trainCount;
      6'b001101:
        casez_tmp_1 = trainCount;
      6'b001110:
        casez_tmp_1 = trainCount;
      6'b001111:
        casez_tmp_1 = trainCount;
      6'b010000:
        casez_tmp_1 = trainCount;
      6'b010001:
        casez_tmp_1 = trainCount;
      6'b010010:
        casez_tmp_1 = trainCount;
      6'b010011:
        casez_tmp_1 = trainCount;
      6'b010100:
        casez_tmp_1 = trainCount;
      6'b010101:
        casez_tmp_1 = trainCount;
      6'b010110:
        casez_tmp_1 = trainCount;
      6'b010111:
        casez_tmp_1 = trainCount;
      6'b011000:
        casez_tmp_1 = trainCount;
      6'b011001:
        casez_tmp_1 = trainCount;
      6'b011010:
        casez_tmp_1 = trainCount;
      6'b011011:
        casez_tmp_1 = trainCount;
      6'b011100:
        casez_tmp_1 = trainCount;
      6'b011101:
        casez_tmp_1 = trainCount;
      6'b011110:
        casez_tmp_1 = trainCount;
      6'b011111:
        casez_tmp_1 = trainCount;
      6'b100000:
        casez_tmp_1 = trainCount;
      6'b100001:
        casez_tmp_1 = trainCount;
      6'b100010:
        casez_tmp_1 = trainCount;
      6'b100011:
        casez_tmp_1 = trainCount;
      6'b100100:
        casez_tmp_1 = trainCount;
      6'b100101:
        casez_tmp_1 = _GEN_105;
      6'b100110:
        casez_tmp_1 = trainCount;
      6'b100111:
        casez_tmp_1 = trainCount;
      6'b101000:
        casez_tmp_1 = trainCount;
      6'b101001:
        casez_tmp_1 = trainCount;
      6'b101010:
        casez_tmp_1 = _GEN_105;
      6'b101011:
        casez_tmp_1 = _GEN_105;
      6'b101100:
        casez_tmp_1 = _GEN_105;
      6'b101101:
        casez_tmp_1 = _GEN_105;
      6'b101110:
        casez_tmp_1 = _GEN_105;
      6'b101111:
        casez_tmp_1 = _GEN_105;
      6'b110000:
        casez_tmp_1 = _GEN_105;
      6'b110001:
        casez_tmp_1 = _GEN_105;
      6'b110010:
        casez_tmp_1 = _GEN_105;
      6'b110011:
        casez_tmp_1 = _GEN_105;
      6'b110100:
        casez_tmp_1 = _GEN_105;
      6'b110101:
        casez_tmp_1 = _GEN_105;
      6'b110110:
        casez_tmp_1 = _GEN_105;
      6'b110111:
        casez_tmp_1 = _GEN_105;
      6'b111000:
        casez_tmp_1 = _GEN_105;
      6'b111001:
        casez_tmp_1 = _GEN_105;
      6'b111010:
        casez_tmp_1 = _GEN_105;
      6'b111011:
        casez_tmp_1 = _GEN_105;
      6'b111100:
        casez_tmp_1 = _GEN_105;
      6'b111101:
        casez_tmp_1 = _GEN_105;
      6'b111110:
        casez_tmp_1 = _GEN_105;
      default:
        casez_tmp_1 = _GEN_105;
    endcase
  end // always_comb
  assign _GEN_106 = commandDone ? 6'h6 : state;
  assign _GEN_107 = spiDone ? 6'h22 : state;
  assign _GEN_108 = _GEN_99 ? 6'h1 : state;
  always_comb begin
    casez (state)
      6'b000000:
        casez_tmp_2 = _GEN_25 ? 6'h1 : state;
      6'b000001:
        casez_tmp_2 = spiDone & _GEN_30 ? 6'h2 : state;
      6'b000010:
        casez_tmp_2 = _GEN_5 ? 6'h3 : state;
      6'b000011:
        casez_tmp_2 = _GEN_34 ? 6'h25 : commandDone ? 6'h4 : state;
      6'b000100:
        casez_tmp_2 = _GEN_5 ? 6'h5 : state;
      6'b000101:
        casez_tmp_2 =
          commandFailed
            ? 6'h25
            : _GEN_37
                ? (_GEN_38 ? 6'h25 : 6'h28)
                : _GEN_39 ? 6'h28 : commandDone ? 6'h25 : state;
      6'b000110:
        casez_tmp_2 = _GEN_5 ? 6'h7 : state;
      6'b000111:
        casez_tmp_2 = _GEN_46 ? 6'h25 : commandDone ? 6'h8 : state;
      6'b001000:
        casez_tmp_2 = _GEN_5 ? 6'h9 : state;
      6'b001001:
        casez_tmp_2 =
          _GEN_46
            ? 6'h25
            : _GEN_49 ? (version2 ? 6'hA : 6'hC) : _GEN_50 ? 6'h25 : _GEN_106;
      6'b001010:
        casez_tmp_2 = _GEN_5 ? 6'hB : state;
      6'b001011:
        casez_tmp_2 =
          _GEN_54 ? 6'h25 : commandDone ? {4'h3, commandExtra_0[6], 1'h0} : state;
      6'b001100:
        casez_tmp_2 = _GEN_5 ? 6'hD : state;
      6'b001101:
        casez_tmp_2 = _GEN_54 ? 6'h25 : commandDone ? 6'hE : state;
      6'b001110:
        casez_tmp_2 = _GEN_57 ? (io_block_request_bits_write ? 6'h18 : 6'hF) : state;
      6'b001111:
        casez_tmp_2 = _GEN_5 ? 6'h10 : state;
      6'b010000:
        casez_tmp_2 = _GEN_54 ? 6'h24 : commandDone ? 6'h11 : state;
      6'b010001:
        casez_tmp_2 = spiBusy ? state : 6'h12;
      6'b010010:
        casez_tmp_2 = _GEN_63 ? 6'h13 : _GEN_64 ? 6'h24 : spiDone ? 6'h11 : state;
      6'b010011:
        casez_tmp_2 = spiBusy ? state : 6'h14;
      6'b010100:
        casez_tmp_2 = spiDone ? 6'h15 : state;
      6'b010101:
        casez_tmp_2 = _GEN_68 ? (_GEN_69 ? 6'h16 : 6'h13) : state;
      6'b010110:
        casez_tmp_2 = spiBusy ? state : 6'h17;
      6'b010111:
        casez_tmp_2 = spiDone ? (crcIndex ? 6'h26 : 6'h16) : state;
      6'b011000:
        casez_tmp_2 = _GEN_5 ? 6'h19 : state;
      6'b011001:
        casez_tmp_2 = _GEN_54 ? 6'h24 : commandDone ? 6'h1A : state;
      6'b011010:
        casez_tmp_2 = spiBusy ? state : 6'h1B;
      6'b011011:
        casez_tmp_2 = spiDone ? 6'h1C : state;
      6'b011100:
        casez_tmp_2 = _GEN_81 ? 6'h1D : state;
      6'b011101:
        casez_tmp_2 = spiDone ? {4'h7, _GEN_69, 1'h0} : state;
      6'b011110:
        casez_tmp_2 = spiBusy ? state : 6'h1F;
      6'b011111:
        casez_tmp_2 = spiDone ? (crcIndex ? 6'h20 : 6'h1E) : state;
      6'b100000:
        casez_tmp_2 = spiBusy ? state : 6'h21;
      6'b100001:
        casez_tmp_2 = _GEN_87 ? 6'h24 : _GEN_107;
      6'b100010:
        casez_tmp_2 = spiBusy ? state : 6'h23;
      6'b100011:
        casez_tmp_2 = _GEN_90 ? 6'h26 : _GEN_64 ? 6'h24 : _GEN_107;
      6'b100100:
        casez_tmp_2 = 6'hE;
      6'b100101:
        casez_tmp_2 = _GEN_108;
      6'b100110:
        casez_tmp_2 = spiBusy ? state : 6'h27;
      6'b100111:
        casez_tmp_2 = spiDone ? 6'h24 : state;
      6'b101000:
        casez_tmp_2 = _GEN_5 ? 6'h29 : state;
      6'b101001:
        casez_tmp_2 = _GEN_34 ? 6'h25 : _GEN_106;
      6'b101010:
        casez_tmp_2 = _GEN_108;
      6'b101011:
        casez_tmp_2 = _GEN_108;
      6'b101100:
        casez_tmp_2 = _GEN_108;
      6'b101101:
        casez_tmp_2 = _GEN_108;
      6'b101110:
        casez_tmp_2 = _GEN_108;
      6'b101111:
        casez_tmp_2 = _GEN_108;
      6'b110000:
        casez_tmp_2 = _GEN_108;
      6'b110001:
        casez_tmp_2 = _GEN_108;
      6'b110010:
        casez_tmp_2 = _GEN_108;
      6'b110011:
        casez_tmp_2 = _GEN_108;
      6'b110100:
        casez_tmp_2 = _GEN_108;
      6'b110101:
        casez_tmp_2 = _GEN_108;
      6'b110110:
        casez_tmp_2 = _GEN_108;
      6'b110111:
        casez_tmp_2 = _GEN_108;
      6'b111000:
        casez_tmp_2 = _GEN_108;
      6'b111001:
        casez_tmp_2 = _GEN_108;
      6'b111010:
        casez_tmp_2 = _GEN_108;
      6'b111011:
        casez_tmp_2 = _GEN_108;
      6'b111100:
        casez_tmp_2 = _GEN_108;
      6'b111101:
        casez_tmp_2 = _GEN_108;
      6'b111110:
        casez_tmp_2 = _GEN_108;
      default:
        casez_tmp_2 = _GEN_108;
    endcase
  end // always_comb
  assign _GEN_109 = _GEN_34 ? 24'h0 : initWait;
  assign _GEN_110 = _GEN_54 ? 24'h0 : initWait;
  assign _GEN_111 = _GEN_101 | ~_GEN_97 ? initWait : _GEN_98 ? 24'h0 : initWait + 24'h1;
  always_comb begin
    casez (state)
      6'b000000:
        casez_tmp_3 = _GEN_25 ? 24'h0 : initWait + 24'h1;
      6'b000001:
        casez_tmp_3 = initWait;
      6'b000010:
        casez_tmp_3 = initWait;
      6'b000011:
        casez_tmp_3 = _GEN_109;
      6'b000100:
        casez_tmp_3 = initWait;
      6'b000101:
        casez_tmp_3 =
          commandFailed
            ? 24'h0
            : _GEN_37 ? (_GEN_38 ? 24'h0 : initWait) : _GEN_40 ? initWait : 24'h0;
      6'b000110:
        casez_tmp_3 = initWait;
      6'b000111:
        casez_tmp_3 = _GEN_46 ? 24'h0 : initWait;
      6'b001000:
        casez_tmp_3 = initWait;
      6'b001001:
        casez_tmp_3 = _GEN_46 | ~_GEN_51 ? 24'h0 : initWait;
      6'b001010:
        casez_tmp_3 = initWait;
      6'b001011:
        casez_tmp_3 = _GEN_110;
      6'b001100:
        casez_tmp_3 = initWait;
      6'b001101:
        casez_tmp_3 = _GEN_110;
      6'b001110:
        casez_tmp_3 = initWait;
      6'b001111:
        casez_tmp_3 = initWait;
      6'b010000:
        casez_tmp_3 = initWait;
      6'b010001:
        casez_tmp_3 = initWait;
      6'b010010:
        casez_tmp_3 = initWait;
      6'b010011:
        casez_tmp_3 = initWait;
      6'b010100:
        casez_tmp_3 = initWait;
      6'b010101:
        casez_tmp_3 = initWait;
      6'b010110:
        casez_tmp_3 = initWait;
      6'b010111:
        casez_tmp_3 = initWait;
      6'b011000:
        casez_tmp_3 = initWait;
      6'b011001:
        casez_tmp_3 = initWait;
      6'b011010:
        casez_tmp_3 = initWait;
      6'b011011:
        casez_tmp_3 = initWait;
      6'b011100:
        casez_tmp_3 = initWait;
      6'b011101:
        casez_tmp_3 = initWait;
      6'b011110:
        casez_tmp_3 = initWait;
      6'b011111:
        casez_tmp_3 = initWait;
      6'b100000:
        casez_tmp_3 = initWait;
      6'b100001:
        casez_tmp_3 = initWait;
      6'b100010:
        casez_tmp_3 = initWait;
      6'b100011:
        casez_tmp_3 = initWait;
      6'b100100:
        casez_tmp_3 = initWait;
      6'b100101:
        casez_tmp_3 = _GEN_111;
      6'b100110:
        casez_tmp_3 = initWait;
      6'b100111:
        casez_tmp_3 = initWait;
      6'b101000:
        casez_tmp_3 = initWait;
      6'b101001:
        casez_tmp_3 = _GEN_109;
      6'b101010:
        casez_tmp_3 = _GEN_111;
      6'b101011:
        casez_tmp_3 = _GEN_111;
      6'b101100:
        casez_tmp_3 = _GEN_111;
      6'b101101:
        casez_tmp_3 = _GEN_111;
      6'b101110:
        casez_tmp_3 = _GEN_111;
      6'b101111:
        casez_tmp_3 = _GEN_111;
      6'b110000:
        casez_tmp_3 = _GEN_111;
      6'b110001:
        casez_tmp_3 = _GEN_111;
      6'b110010:
        casez_tmp_3 = _GEN_111;
      6'b110011:
        casez_tmp_3 = _GEN_111;
      6'b110100:
        casez_tmp_3 = _GEN_111;
      6'b110101:
        casez_tmp_3 = _GEN_111;
      6'b110110:
        casez_tmp_3 = _GEN_111;
      6'b110111:
        casez_tmp_3 = _GEN_111;
      6'b111000:
        casez_tmp_3 = _GEN_111;
      6'b111001:
        casez_tmp_3 = _GEN_111;
      6'b111010:
        casez_tmp_3 = _GEN_111;
      6'b111011:
        casez_tmp_3 = _GEN_111;
      6'b111100:
        casez_tmp_3 = _GEN_111;
      6'b111101:
        casez_tmp_3 = _GEN_111;
      6'b111110:
        casez_tmp_3 = _GEN_111;
      default:
        casez_tmp_3 = _GEN_111;
    endcase
  end // always_comb
  assign _GEN_112 = _GEN_54 | failed;
  assign _GEN_113 = _GEN_54 | operationError;
  assign _GEN_114 = _GEN_34 | failed;
  assign _GEN_115 = ~_GEN_34 & initialized;
  assign _GEN_116 = _GEN_34 | operationError;
  assign _readCrc_T_3 =
    {readCrc[14:0], 1'h0} ^ (readCrc[15] ^ spiRxShift[7] ? 16'h1021 : 16'h0);
  assign _readCrc_T_7 =
    {_readCrc_T_3[14:0], 1'h0} ^ (_readCrc_T_3[15] ^ spiRxShift[6] ? 16'h1021 : 16'h0);
  assign _readCrc_T_11 =
    {_readCrc_T_7[14:0], 1'h0} ^ (_readCrc_T_7[15] ^ spiRxShift[5] ? 16'h1021 : 16'h0);
  assign _readCrc_T_15 =
    {_readCrc_T_11[14:0], 1'h0} ^ (_readCrc_T_11[15] ^ spiRxShift[4] ? 16'h1021 : 16'h0);
  assign _readCrc_T_19 =
    {_readCrc_T_15[14:0], 1'h0} ^ (_readCrc_T_15[15] ^ spiRxShift[3] ? 16'h1021 : 16'h0);
  assign _readCrc_T_23 =
    {_readCrc_T_19[14:0], 1'h0} ^ (_readCrc_T_19[15] ^ spiRxShift[2] ? 16'h1021 : 16'h0);
  assign _readCrc_T_27 =
    {_readCrc_T_23[14:0], 1'h0} ^ (_readCrc_T_23[15] ^ spiRxShift[1] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_3 =
    {writeCrc[14:0], 1'h0} ^ (writeCrc[15] ^ io_block_write_bits[7] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_7 =
    {_writeCrc_T_3[14:0], 1'h0}
    ^ (_writeCrc_T_3[15] ^ io_block_write_bits[6] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_11 =
    {_writeCrc_T_7[14:0], 1'h0}
    ^ (_writeCrc_T_7[15] ^ io_block_write_bits[5] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_15 =
    {_writeCrc_T_11[14:0], 1'h0}
    ^ (_writeCrc_T_11[15] ^ io_block_write_bits[4] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_19 =
    {_writeCrc_T_15[14:0], 1'h0}
    ^ (_writeCrc_T_15[15] ^ io_block_write_bits[3] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_23 =
    {_writeCrc_T_19[14:0], 1'h0}
    ^ (_writeCrc_T_19[15] ^ io_block_write_bits[2] ? 16'h1021 : 16'h0);
  assign _writeCrc_T_27 =
    {_writeCrc_T_23[14:0], 1'h0}
    ^ (_writeCrc_T_23[15] ^ io_block_write_bits[1] ? 16'h1021 : 16'h0);
  assign _GEN_117 = _GEN_70 | _GEN_71 | _GEN_72 | _GEN_78 | _GEN_79;
  assign halfTicks = spiFast ? 6'h5 : 6'h3D;
  assign _GEN_118 = spiDone & ~(spiRxShift[7]);
  assign _GEN_119 = _GEN_7 | _GEN_8 | _GEN_10;
  assign _GEN_120 = _GEN_6 | _GEN_7 | _GEN_8 | _GEN_10 | _GEN_11 | _GEN_14;
  assign _GEN_121 = _GEN_34 | csN;
  assign _GEN_122 = ~_GEN_39 & commandDone;
  assign _GEN_123 = ~_GEN_49 & _GEN_50;
  assign _GEN_124 = _GEN_54 | csN;
  assign _GEN_125 = _GEN_54 | ~commandDone;
  assign _GEN_126 = commandDone & commandExtra_0[6];
  assign _GEN_127 =
    _GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42
    | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55 | _GEN_56;
  assign _GEN_128 = _GEN_66 & spiDone;
  assign _GEN_129 = _GEN_58 | _GEN_60 | _GEN_61 | _GEN_62 | _GEN_65;
  assign _GEN_130 = spiDone & ~crcIndex;
  assign _GEN_131 = _GEN_65 | _GEN_66 | _GEN_67 | _GEN_70;
  assign _GEN_132 = _GEN_65 | _GEN_66;
  assign _GEN_133 =
    _GEN_58 | _GEN_60 | _GEN_61 | _GEN_62 | _GEN_65 | _GEN_66 | _GEN_67 | _GEN_70
    | _GEN_71 | _GEN_72 | _GEN_78 | _GEN_79 | _GEN_80 | _io_block_write_ready_T | _GEN_82
    | _GEN_83 | _GEN_84 | _GEN_85 | _GEN_86 | _GEN_88 | _GEN_89 | _GEN_91 | _GEN_95;
  assign _GEN_134 = _GEN_100 | ~_GEN_99;
  assign _GEN_135 =
    _GEN_79 | _GEN_80 | _io_block_write_ready_T | _GEN_82 | _GEN_83 | _GEN_84 | _GEN_85;
  assign _GEN_136 = _GEN_101 | ~_GEN_99;
  assign _GEN_137 = _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52;
  assign _commandCrcReg_T_10 = commandNumber[5] ? 7'h9 : 7'h0;
  assign _commandCrcReg_T_15 =
    {_commandCrcReg_T_10[5:0] ^ 6'h12, 1'h0}
    ^ (_commandCrcReg_T_10[6] ^ commandNumber[4] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_19 =
    {_commandCrcReg_T_15[5:0], 1'h0}
    ^ (_commandCrcReg_T_15[6] ^ commandNumber[3] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_23 =
    {_commandCrcReg_T_19[5:0], 1'h0}
    ^ (_commandCrcReg_T_19[6] ^ commandNumber[2] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_27 =
    {_commandCrcReg_T_23[5:0], 1'h0}
    ^ (_commandCrcReg_T_23[6] ^ commandNumber[1] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_31 =
    {_commandCrcReg_T_27[5:0], 1'h0}
    ^ (_commandCrcReg_T_27[6] ^ commandNumber[0] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_36 =
    {_commandCrcReg_T_31[5:0], 1'h0}
    ^ (_commandCrcReg_T_31[6] ^ commandArgument[31] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_40 =
    {_commandCrcReg_T_36[5:0], 1'h0}
    ^ (_commandCrcReg_T_36[6] ^ commandArgument[30] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_44 =
    {_commandCrcReg_T_40[5:0], 1'h0}
    ^ (_commandCrcReg_T_40[6] ^ commandArgument[29] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_48 =
    {_commandCrcReg_T_44[5:0], 1'h0}
    ^ (_commandCrcReg_T_44[6] ^ commandArgument[28] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_52 =
    {_commandCrcReg_T_48[5:0], 1'h0}
    ^ (_commandCrcReg_T_48[6] ^ commandArgument[27] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_56 =
    {_commandCrcReg_T_52[5:0], 1'h0}
    ^ (_commandCrcReg_T_52[6] ^ commandArgument[26] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_60 =
    {_commandCrcReg_T_56[5:0], 1'h0}
    ^ (_commandCrcReg_T_56[6] ^ commandArgument[25] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_64 =
    {_commandCrcReg_T_60[5:0], 1'h0}
    ^ (_commandCrcReg_T_60[6] ^ commandArgument[24] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_69 =
    {_commandCrcReg_T_64[5:0], 1'h0}
    ^ (_commandCrcReg_T_64[6] ^ commandArgument[23] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_73 =
    {_commandCrcReg_T_69[5:0], 1'h0}
    ^ (_commandCrcReg_T_69[6] ^ commandArgument[22] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_77 =
    {_commandCrcReg_T_73[5:0], 1'h0}
    ^ (_commandCrcReg_T_73[6] ^ commandArgument[21] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_81 =
    {_commandCrcReg_T_77[5:0], 1'h0}
    ^ (_commandCrcReg_T_77[6] ^ commandArgument[20] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_85 =
    {_commandCrcReg_T_81[5:0], 1'h0}
    ^ (_commandCrcReg_T_81[6] ^ commandArgument[19] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_89 =
    {_commandCrcReg_T_85[5:0], 1'h0}
    ^ (_commandCrcReg_T_85[6] ^ commandArgument[18] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_93 =
    {_commandCrcReg_T_89[5:0], 1'h0}
    ^ (_commandCrcReg_T_89[6] ^ commandArgument[17] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_97 =
    {_commandCrcReg_T_93[5:0], 1'h0}
    ^ (_commandCrcReg_T_93[6] ^ commandArgument[16] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_102 =
    {_commandCrcReg_T_97[5:0], 1'h0}
    ^ (_commandCrcReg_T_97[6] ^ commandArgument[15] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_106 =
    {_commandCrcReg_T_102[5:0], 1'h0}
    ^ (_commandCrcReg_T_102[6] ^ commandArgument[14] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_110 =
    {_commandCrcReg_T_106[5:0], 1'h0}
    ^ (_commandCrcReg_T_106[6] ^ commandArgument[13] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_114 =
    {_commandCrcReg_T_110[5:0], 1'h0}
    ^ (_commandCrcReg_T_110[6] ^ commandArgument[12] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_118 =
    {_commandCrcReg_T_114[5:0], 1'h0}
    ^ (_commandCrcReg_T_114[6] ^ commandArgument[11] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_122 =
    {_commandCrcReg_T_118[5:0], 1'h0}
    ^ (_commandCrcReg_T_118[6] ^ commandArgument[10] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_126 =
    {_commandCrcReg_T_122[5:0], 1'h0}
    ^ (_commandCrcReg_T_122[6] ^ commandArgument[9] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_130 =
    {_commandCrcReg_T_126[5:0], 1'h0}
    ^ (_commandCrcReg_T_126[6] ^ commandArgument[8] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_135 =
    {_commandCrcReg_T_130[5:0], 1'h0}
    ^ (_commandCrcReg_T_130[6] ^ commandArgument[7] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_139 =
    {_commandCrcReg_T_135[5:0], 1'h0}
    ^ (_commandCrcReg_T_135[6] ^ commandArgument[6] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_143 =
    {_commandCrcReg_T_139[5:0], 1'h0}
    ^ (_commandCrcReg_T_139[6] ^ commandArgument[5] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_147 =
    {_commandCrcReg_T_143[5:0], 1'h0}
    ^ (_commandCrcReg_T_143[6] ^ commandArgument[4] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_151 =
    {_commandCrcReg_T_147[5:0], 1'h0}
    ^ (_commandCrcReg_T_147[6] ^ commandArgument[3] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_155 =
    {_commandCrcReg_T_151[5:0], 1'h0}
    ^ (_commandCrcReg_T_151[6] ^ commandArgument[2] ? 7'h9 : 7'h0);
  assign _commandCrcReg_T_159 =
    {_commandCrcReg_T_155[5:0], 1'h0}
    ^ (_commandCrcReg_T_155[6] ^ commandArgument[1] ? 7'h9 : 7'h0);
  always @(posedge clock) begin
    if (reset) begin
      spiFast <= 1'h0;
      spiBusy <= 1'h0;
      spiSck <= 1'h0;
      spiMosi <= 1'h1;
      spiTimer <= 6'h0;
      spiBit <= 3'h7;
      spiTxShift <= 8'hFF;
      spiRxShift <= 8'h0;
      misoMeta <= 1'h1;
      misoSync <= 1'h1;
      commandState <= 4'h0;
      commandPostClockReg <= 1'h0;
      commandIndex <= 3'h0;
      commandTries <= 7'h0;
      commandExtraIndex <= 3'h0;
      commandResponse <= 8'hFF;
      commandExtra_0 <= 8'h0;
      commandExtra_1 <= 8'h0;
      commandExtra_2 <= 8'h0;
      commandExtra_3 <= 8'h0;
      state <= 6'h0;
      csN <= 1'h1;
      initialized <= 1'h0;
      failed <= 1'h0;
      sdhc <= 1'h1;
      version2 <= 1'h1;
      trainCount <= 4'h0;
      acmdCount <= 14'h0;
      tokenCount <= 16'h0;
      byteIndex <= 10'h0;
      crcIndex <= 1'h0;
      readCrc <= 16'h0;
      readCrcHigh <= 8'h0;
      writeCrc <= 16'h0;
      requestLba <= 32'h0;
      initWait <= 24'h0;
      readValid <= 1'h0;
      readData <= 8'h0;
      done <= 1'h0;
      operationError <= 1'h0;
    end
    else begin
      if (~(_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_137)) begin
        if (_GEN_53)
          spiFast <= ~_GEN_54 & _GEN_126 | spiFast;
        else if (~_GEN_55)
          spiFast <= _GEN_56 ? ~_GEN_54 & commandDone | spiFast : _GEN_136 & spiFast;
      end
      spiBusy <= _GEN_1 | (~_GEN_3 | ~spiSck | ~_GEN_4) & spiBusy;
      spiSck <= ~_GEN_1 & (_GEN_3 ^ spiSck);
      if (_GEN_1) begin
        spiMosi <= spiTx[7];
        spiTimer <= halfTicks;
        spiBit <= 3'h7;
        spiTxShift <= spiTx;
        spiRxShift <= 8'h0;
      end
      else begin
        if (_GEN_3 & spiSck)
          spiMosi <= _GEN_4 | spiTxShift[6];
        if (spiBusy)
          spiTimer <= _GEN_2 ? halfTicks : spiTimer - 6'h1;
        if (~_GEN_3 | ~spiSck | _GEN_4) begin
        end
        else begin
          spiBit <= spiBit - 3'h1;
          spiTxShift <= {spiTxShift[6:0], 1'h1};
        end
        if (spiBusy & _GEN_2 & ~spiSck)
          spiRxShift <= {spiRxShift[6:0], misoSync};
      end
      misoMeta <= io_miso;
      misoSync <= misoMeta;
      if (_GEN_6) begin
        commandState <= 4'h1;
        commandPostClockReg <=
          ~_GEN_76
          & (_GEN_31 | ~_GEN_32
             & (_GEN_35 | ~_GEN_36
                & (_GEN_41 | ~_GEN_42
                   & (_GEN_43 | ~_GEN_44
                      & (_GEN_47 | ~_GEN_48 & (_GEN_52 | ~_GEN_53 & _GEN_55))))))
          & _GEN_5;
        commandIndex <= 3'h0;
        commandTries <= 7'h0;
        commandExtraIndex <= 3'h0;
      end
      else begin
        commandState <= casez_tmp_0;
        if (_GEN_7 | ~(_GEN_8 & spiDone) | _GEN_9) begin
        end
        else
          commandIndex <= commandIndex + 3'h1;
        if (_GEN_119 | ~(_GEN_11 & spiDone) | ~(spiRxShift[7]) | _GEN_13) begin
        end
        else
          commandTries <= commandTries + 7'h1;
        if (~_GEN_119) begin
          if (_GEN_11) begin
            if (~_GEN_118 | _GEN_12) begin
            end
            else
              commandExtraIndex <= 3'h0;
          end
          else if (_GEN_14 | ~(_GEN_15 & spiDone) | _GEN_16) begin
          end
          else
            commandExtraIndex <= commandExtraIndex + 3'h1;
        end
      end
      if (_GEN_6 | _GEN_119 | ~(_GEN_11 & _GEN_118)) begin
      end
      else
        commandResponse <= spiRxShift;
      if (_GEN_120 | ~(_GEN_15 & spiDone & commandExtraIndex[1:0] == 2'h0)) begin
      end
      else
        commandExtra_0 <= spiRxShift;
      if (_GEN_120 | ~(_GEN_15 & spiDone & commandExtraIndex[1:0] == 2'h1)) begin
      end
      else
        commandExtra_1 <= spiRxShift;
      if (_GEN_120 | ~(_GEN_15 & spiDone & commandExtraIndex[1:0] == 2'h2)) begin
      end
      else
        commandExtra_2 <= spiRxShift;
      if (_GEN_120 | ~(_GEN_15 & spiDone & (&(commandExtraIndex[1:0])))) begin
      end
      else
        commandExtra_3 <= spiRxShift;
      state <= casez_tmp_2;
      csN <=
        _GEN_24
        | (_GEN_26
             ? ~spiDone | trainCount != 4'h9
             : _GEN_31
                 ? csN
                 : _GEN_32
                     ? _GEN_121
                     : _GEN_35
                         ? csN
                         : _GEN_36
                             ? commandFailed | (_GEN_37 ? _GEN_38 | csN : _GEN_122 | csN)
                             : _GEN_41
                                 ? csN
                                 : _GEN_42
                                     ? _GEN_121
                                     : _GEN_43
                                         ? csN
                                         : _GEN_44
                                             ? _GEN_46 | csN
                                             : _GEN_47
                                                 ? csN
                                                 : _GEN_48
                                                     ? _GEN_46 | _GEN_123 | csN
                                                     : _GEN_52
                                                         ? csN
                                                         : _GEN_53
                                                             ? _GEN_124
                                                             : _GEN_55
                                                                 ? csN
                                                                 : _GEN_56
                                                                     ? _GEN_124
                                                                     : _io_block_request_ready_T
                                                                         ? ~_GEN_57
                                                                         : ~_GEN_133
                                                                           & (_GEN_96
                                                                              | _GEN_97)
                                                                           | csN);
      if (~(_GEN_24 | _GEN_26 | _GEN_31)) begin
        if (_GEN_32) begin
          initialized <= _GEN_115;
          failed <= _GEN_114;
          operationError <= _GEN_116;
        end
        else if (~_GEN_35) begin
          if (_GEN_36) begin
            initialized <=
              ~commandFailed & (_GEN_37 ? ~_GEN_38 & initialized : _GEN_40 & initialized);
            failed <= commandFailed | (_GEN_37 ? _GEN_38 | failed : _GEN_122 | failed);
            operationError <=
              commandFailed
              | (_GEN_37 ? _GEN_38 | operationError : _GEN_122 | operationError);
          end
          else if (~_GEN_41) begin
            if (_GEN_42) begin
              initialized <= _GEN_115;
              failed <= _GEN_114;
              operationError <= _GEN_116;
            end
            else if (~_GEN_43) begin
              if (_GEN_44) begin
                initialized <= ~_GEN_46 & initialized;
                failed <= _GEN_46 | failed;
                operationError <= _GEN_46 | operationError;
              end
              else if (~_GEN_47) begin
                if (_GEN_48) begin
                  initialized <= ~_GEN_46 & _GEN_51 & initialized;
                  failed <= _GEN_46 | _GEN_123 | failed;
                  operationError <= _GEN_46 | _GEN_123 | operationError;
                end
                else if (~_GEN_52) begin
                  if (_GEN_53) begin
                    initialized <= ~_GEN_54 & (_GEN_126 | initialized);
                    failed <= _GEN_112;
                    operationError <= _GEN_113;
                  end
                  else begin
                    if (_GEN_55 | ~_GEN_56) begin
                    end
                    else
                      initialized <= ~_GEN_54 & (commandDone | initialized);
                    if (~_GEN_55) begin
                      failed <= _GEN_56 ? _GEN_112 : _GEN_136 & failed;
                      operationError <=
                        _GEN_56
                          ? _GEN_113
                          : ~_io_block_request_ready_T
                            & (_GEN_58
                                 ? operationError
                                 : _GEN_60
                                     ? _GEN_113
                                     : _GEN_61
                                         ? operationError
                                         : _GEN_62
                                             ? ~_GEN_63 & _GEN_64 | operationError
                                             : _GEN_131
                                                 ? operationError
                                                 : _GEN_71
                                                     ? spiDone
                                                       & ~(~crcIndex
                                                           | {readCrcHigh,
                                                              spiRxShift} == readCrc)
                                                       | operationError
                                                     : _GEN_72
                                                         ? operationError
                                                         : _GEN_78
                                                             ? _GEN_113
                                                             : _GEN_135
                                                                 ? operationError
                                                                 : _GEN_86
                                                                     ? _GEN_87
                                                                       | operationError
                                                                     : _GEN_88
                                                                         ? operationError
                                                                         : _GEN_89
                                                                             ? ~_GEN_90
                                                                               & _GEN_64
                                                                               | operationError
                                                                             : _GEN_134
                                                                               & operationError);
                    end
                  end
                end
              end
            end
          end
        end
      end
      if (~(_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35)) begin
        if (_GEN_36) begin
          sdhc <= (commandFailed | _GEN_37 | ~_GEN_39) & sdhc;
          if (commandFailed) begin
          end
          else begin
            version2 <= _GEN_37 ? ~_GEN_38 | version2 : ~_GEN_39 & version2;
            if (_GEN_37) begin
              if (~_GEN_38)
                acmdCount <= 14'h0;
            end
            else if (_GEN_39)
              acmdCount <= 14'h0;
          end
        end
        else begin
          if (~_GEN_137) begin
            if (_GEN_53) begin
              if (_GEN_125) begin
              end
              else
                sdhc <= commandExtra_0[6];
            end
            else
              sdhc <= ~_GEN_102 & _GEN_99 | sdhc;
          end
          version2 <= ~_GEN_104 & _GEN_99 | version2;
          if (~(_GEN_41 | _GEN_42 | _GEN_43 | _GEN_44 | _GEN_47)) begin
            if (_GEN_48) begin
              if (_GEN_46 | _GEN_49 | _GEN_50 | ~commandDone) begin
              end
              else
                acmdCount <= acmdCount + 14'h1;
            end
            else if (_GEN_103 | ~_GEN_99) begin
            end
            else
              acmdCount <= 14'h0;
          end
        end
      end
      trainCount <= casez_tmp_1;
      if (~_GEN_127) begin
        if (_io_block_request_ready_T) begin
          if (_GEN_57) begin
            tokenCount <= 16'h0;
            byteIndex <= 10'h0;
            readCrc <= 16'h0;
            writeCrc <= 16'h0;
          end
        end
        else begin
          if (~_GEN_58) begin
            if (_GEN_60) begin
              if (_GEN_125) begin
              end
              else
                tokenCount <= 16'h0;
            end
            else if (~_GEN_61) begin
              if (_GEN_62) begin
                if (_GEN_63 | _GEN_64 | ~spiDone) begin
                end
                else
                  tokenCount <= tokenCount + 16'h1;
              end
              else if (~(_GEN_65 | _GEN_66 | _GEN_67 | _GEN_70 | _GEN_71 | _GEN_72
                         | _GEN_78 | _GEN_135)) begin
                if (_GEN_86) begin
                  if (_GEN_87 | ~spiDone) begin
                  end
                  else
                    tokenCount <= 16'h0;
                end
                else if (~_GEN_88) begin
                  if (_GEN_89) begin
                    if (_GEN_90 | _GEN_64 | ~spiDone) begin
                    end
                    else
                      tokenCount <= tokenCount + 16'h1;
                  end
                  else if (_GEN_134) begin
                  end
                  else
                    tokenCount <= 16'h0;
                end
              end
            end
          end
          if (~(_GEN_58 | _GEN_60 | _GEN_61)) begin
            if (_GEN_62) begin
              if (_GEN_63) begin
                byteIndex <= 10'h0;
                readCrc <= 16'h0;
              end
            end
            else begin
              if (~_GEN_132) begin
                if (_GEN_67) begin
                  if (~_GEN_68 | _GEN_69) begin
                  end
                  else
                    byteIndex <= byteIndex + 10'h1;
                end
                else if (~_GEN_117) begin
                  if (_GEN_80) begin
                    if (spiDone)
                      byteIndex <= 10'h0;
                  end
                  else if (_io_block_write_ready_T | ~(_GEN_82 & spiDone) | _GEN_69) begin
                  end
                  else
                    byteIndex <= byteIndex + 10'h1;
                end
              end
              if (_GEN_65 | ~_GEN_128) begin
              end
              else
                readCrc <=
                  {_readCrc_T_27[14:0], 1'h0}
                  ^ (_readCrc_T_27[15] ^ spiRxShift[0] ? 16'h1021 : 16'h0);
            end
          end
          if (~(_GEN_58 | _GEN_60 | _GEN_61 | _GEN_62 | _GEN_65 | _GEN_66 | _GEN_67
                | _GEN_117)) begin
            if (_GEN_80) begin
              if (spiDone)
                writeCrc <= 16'h0;
            end
            else if (_GEN_81)
              writeCrc <=
                {_writeCrc_T_27[14:0], 1'h0}
                ^ (_writeCrc_T_27[15] ^ io_block_write_bits[0] ? 16'h1021 : 16'h0);
          end
        end
        readValid <=
          ~_io_block_request_ready_T
          & (_GEN_129
               ? readValid
               : _GEN_66 ? spiDone | readValid : ~(_GEN_67 & _GEN_68) & readValid);
      end
      if (~(_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42
            | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55
            | _GEN_56 | _io_block_request_ready_T | _GEN_58 | _GEN_60 | _GEN_61 | _GEN_62
            | _GEN_132)) begin
        if (_GEN_67)
          crcIndex <= ~(_GEN_68 & _GEN_69) & crcIndex;
        else if (~_GEN_70) begin
          if (_GEN_71)
            crcIndex <= _GEN_130 | crcIndex;
          else if (~(_GEN_72 | _GEN_78 | _GEN_79 | _GEN_80 | _io_block_write_ready_T))
            crcIndex <=
              _GEN_82
                ? ~(spiDone & _GEN_69) & crcIndex
                : ~_GEN_83 & _GEN_84 & spiDone | crcIndex;
        end
      end
      if (_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42
          | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55 | _GEN_56
          | _io_block_request_ready_T | _GEN_58 | _GEN_60 | _GEN_61 | _GEN_62 | _GEN_131
          | ~(_GEN_71 & _GEN_130)) begin
      end
      else
        readCrcHigh <= spiRxShift;
      if (_GEN_127 | ~(_io_block_request_ready_T & _GEN_57)) begin
      end
      else
        requestLba <= io_block_request_bits_lba;
      initWait <= casez_tmp_3;
      if (_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42
          | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55 | _GEN_56
          | _io_block_request_ready_T | _GEN_129 | ~_GEN_128) begin
      end
      else
        readData <= spiRxShift;
      done <=
        ~(_GEN_24 | _GEN_26 | _GEN_31 | _GEN_32 | _GEN_35 | _GEN_36 | _GEN_41 | _GEN_42
          | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48 | _GEN_52 | _GEN_53 | _GEN_55 | _GEN_56
          | _io_block_request_ready_T | _GEN_133) & _GEN_96;
    end
    if (_GEN_6) begin
      commandNumberReg <= commandNumber;
      commandArgumentReg <= commandArgument;
      commandCrcReg <=
        {{_commandCrcReg_T_159[5:0], 1'h0}
           ^ (_commandCrcReg_T_159[6] ^ commandArgument[0] ? 7'h9 : 7'h0),
         1'h1};
      commandExtraCountReg <=
        _GEN_77
          ? 3'h0
          : _GEN_35
              ? {_GEN_5, 2'h0}
              : _GEN_36 | _GEN_41 | _GEN_42 | _GEN_43 | _GEN_44 | _GEN_47 | _GEN_48
                  ? 3'h0
                  : {_GEN_52 & _GEN_5, 2'h0};
    end
  end // always @(posedge)
  assign io_block_request_ready = io_block_request_ready_0;
  assign io_block_read_valid = readValid;
  assign io_block_read_bits = readData;
  assign io_block_write_ready = io_block_write_ready_0;
  assign io_block_done = done;
  assign io_block_error = failed | operationError;
  assign io_block_initialized = initialized;
  assign io_sck = spiSck;
  assign io_mosi = spiMosi;
  assign io_csN = csN;
  assign io_active = state != 6'hE & state != 6'h25;
endmodule

